import { sha256 } from "../digest";
import type { ComposeStamp, MigrationOrigin } from "./types";

/** The line a composed migration carries its provenance on. @internal */
export const COMPOSE_STAMP = "-- forge:compose ";

/** The line a hand-written migration carries so lint knows it is meant to be one. @internal */
export const CUSTOM_STAMP = "-- forge:custom ";

const GENERATED_NOTICE = "-- Generated by `forge db migrate compose`. Do not edit — change schema.sql and compose again.";
const CUSTOM_NOTICE = "-- Custom migration, hand-written: a data move or a step compose cannot express.";

/** The two header lines of a composed migration, over the body they stamp. @internal */
export function formatComposeHeader(stamp: Omit<ComposeStamp, "body">, body: string): string {
  const covered = `${GENERATED_NOTICE}\n${COMPOSE_STAMP}\n${body}`;
  const full: ComposeStamp = { desired: stamp.desired, baseline: stamp.baseline, body: sha256(covered), forge: stamp.forge };
  return `${GENERATED_NOTICE}\n${COMPOSE_STAMP}${JSON.stringify(full)}\n`;
}

/** The two header lines of a custom migration. @internal */
export function formatCustomHeader(): string {
  return `${CUSTOM_NOTICE}\n${CUSTOM_STAMP}{}\n`;
}

/** The line a stamp sits on — the file's first or its second — or -1 when it carries none. */
function stampLine(lines: readonly string[], stamp: string): number {
  return [0, 1].find((index) => (lines[index] ?? "").startsWith(stamp)) ?? -1;
}

/** What a migration file's header says about it: its origin, its stamp when composed, the SQL under the header, and the text the stamp's body digest covers. @internal */
export function parseMigrationHeader(sql: string): { origin: MigrationOrigin; stamp: ComposeStamp | null; body: string; covered: string } {
  const lines = sql.split("\n");
  const composed = stampLine(lines, COMPOSE_STAMP);
  if (composed !== -1) {
    const body = lines.slice(composed + 1).join("\n");
    const covered = [...lines.slice(0, composed), COMPOSE_STAMP, ...lines.slice(composed + 1)].join("\n");
    try {
      const parsed = JSON.parse((lines[composed] ?? "").slice(COMPOSE_STAMP.length)) as Partial<ComposeStamp>;
      if (typeof parsed.desired === "object" && parsed.desired !== null && typeof parsed.body === "string") {
        return {
          origin: "generated",
          stamp: { desired: parsed.desired, baseline: parsed.baseline ?? "", body: parsed.body, forge: parsed.forge ?? "" },
          body,
          covered,
        };
      }
    } catch {
      // A stamp that does not parse is an edited header, which `generated-edited` reports below as a body that no longer hashes.
    }
    return { origin: "generated", stamp: { desired: {}, baseline: "", body: "", forge: "" }, body, covered };
  }
  const custom = stampLine(lines, CUSTOM_STAMP);
  if (custom !== -1) return { origin: "custom", stamp: null, body: lines.slice(custom + 1).join("\n"), covered: sql };
  return { origin: "custom", stamp: null, body: sql, covered: sql };
}
