import { describe, expect, it } from "bun:test";

import { sha256 } from "../digest";
import { COMPOSE_STAMP, formatComposeHeader, formatCustomHeader, parseMigrationHeader } from "./header";

describe("compose header", () => {
  const body = "CREATE TABLE t (id INTEGER);\n";
  const header = formatComposeHeader({ desired: { app: "d".repeat(64) }, baseline: "b".repeat(64), forge: "0.1.10" }, body);

  const covered = `-- Generated by \`forge db migrate compose\`. Do not edit — change schema.sql and compose again.\n-- forge:compose \n${body}`;

  it("is two lines: the notice and the stamp, whose body hash covers every byte outside the stamp JSON", () => {
    const lines = header.split("\n");
    expect(lines[0]).toBe("-- Generated by `forge db migrate compose`. Do not edit — change schema.sql and compose again.");
    expect(lines[1]).toBe(
      `-- forge:compose {"desired":{"app":"${"d".repeat(64)}"},"baseline":"${"b".repeat(64)}","body":"${sha256(covered)}","forge":"0.1.10"}`,
    );
    expect(lines.length).toBe(3);
  });

  it("parses back to a generated origin whose stamp hashes the covered text", () => {
    const parsed = parseMigrationHeader(header + body);
    expect(parsed.origin).toBe("generated");
    expect(parsed.stamp?.body).toBe(sha256(parsed.covered));
    expect(parsed.covered).toBe(covered);
    expect(parsed.body).toBe(body);
  });

  it("reads a compose stamp on the first line, covering the file without its JSON", () => {
    const parsed = parseMigrationHeader(`-- forge:compose {"desired":{},"body":"x"}\n${body}`);
    expect(parsed.origin).toBe("generated");
    expect(parsed.covered).toBe(`-- forge:compose \n${body}`);
    expect(parsed.body).toBe(body);
  });

  it("reads the same stamp whether it sits on line 0 or line 1, blanking only its JSON", () => {
    const json = `{"desired":{"app":"d"},"baseline":"b","body":"c","forge":"0.1.10"}`;
    const first = parseMigrationHeader(`${COMPOSE_STAMP}${json}\n${body}`);
    const second = parseMigrationHeader(`-- a notice\n${COMPOSE_STAMP}${json}\n${body}`);

    expect(first.origin).toBe("generated");
    expect(second.origin).toBe("generated");
    expect(first.stamp).toEqual({ desired: { app: "d" }, baseline: "b", body: "c", forge: "0.1.10" });
    expect(second.stamp).toEqual(first.stamp);
    expect(first.covered).toBe(`${COMPOSE_STAMP}\n${body}`);
    expect(second.covered).toBe(`-- a notice\n${COMPOSE_STAMP}\n${body}`);
    expect(second.body).toBe(body);
  });

  it("reads a custom stamp on either line and treats no stamp as custom", () => {
    expect(parseMigrationHeader(`${formatCustomHeader()}UPDATE t SET a = 1 WHERE id = 1;`)).toEqual({
      origin: "custom",
      stamp: null,
      body: "UPDATE t SET a = 1 WHERE id = 1;",
      covered: `${formatCustomHeader()}UPDATE t SET a = 1 WHERE id = 1;`,
    });
    expect(parseMigrationHeader("-- forge:custom {}\nSELECT 1;").body).toBe("SELECT 1;");
    expect(parseMigrationHeader("-- Migration 0001\nCREATE TABLE t (id);")).toEqual({
      origin: "custom",
      stamp: null,
      body: "-- Migration 0001\nCREATE TABLE t (id);",
      covered: "-- Migration 0001\nCREATE TABLE t (id);",
    });
  });

  it("still reads a generated file whose stamp was mangled, so lint can report the edit", () => {
    const parsed = parseMigrationHeader("-- Generated\n-- forge:compose {not json\nSELECT 1;");
    expect(parsed.origin).toBe("generated");
    expect(parsed.stamp?.body).toBe("");
  });
});
