/** Markdown the viewport must hand back byte for byte: odd list markers, setext headings, escapes, trailing whitespace, LF only, the dialect, an id-form wikilink, and no trailing newline. */
export const ROUND_TRIP_MARKDOWN = [
  "Setext title",
  "============",
  "",
  "Setext subtitle",
  "---------------",
  "",
  "# ATX heading with *emphasis* and `code`",
  "",
  "Hard break with two trailing spaces  ",
  "next line, then a trailing tab\t",
  "and \\*escaped stars\\*, \\[not a link\\], \\#not-a-tag, \\=\\=not hl\\=\\= and a \\\\ backslash.",
  "",
  "* star item",
  "* star item with **bold** and ~~strike~~",
  "",
  "+ plus item",
  '+ plus item with [a link](https://example.com/a "title")',
  "",
  "1) paren ordered",
  "2) second with [[Some Page]]",
  "",
  "- [ ] task due:2026-10-02",
  "- [x] done task #project/alpha",
  "",
  "See [[page|the alias]] and [[Other Page]] tagged #idea and #area/sub, with ==highlighted text== inline.",
  "",
  "> [!note] A callout title",
  "> Callout body with #tag and [[page|alias]].",
  "",
  "> plain quote",
  "",
  "```ts",
  'const x = "**not bold**"; // [[not a link]] #not-tag',
  "```",
  "",
  "Inline `code with ==marks==` and *em* and _em_ and __strong__.",
  "",
  "***",
  "",
  "Final line without a trailing newline",
  "",
  "Linked by id: [[0190c7a0-0000-7000-8000-000000000001|Linked page]] stays as typed.",
].join("\n");
