import type { FontEmit, FontPackData } from "./types";

/** The names the emitted module exports under when the `emit` block does not choose its own. @internal */
export const DEFAULT_FACE_EXPORTS = { fonts: "FACES", defaults: "DEFAULT_FACES" } as const;

const HEADER = [
  "// AUTO-GENERATED by @y-core/forge from the `fonts.emit` block of assets.config.ts — do not edit.",
  "// Each face carries its own subset bytes, so a Worker embeds a document's faces without a fetch.",
].join("\n");

// Chunked because a whole face is six figures of bytes and spreading that into one call is what
// overflows the argument stack; `btoa` is the exact inverse of the `bytes()` the module ships with.
function base64(bytes: Uint8Array): string {
  let binary = "";
  for (let at = 0; at < bytes.length; at += 0x8000) binary += String.fromCharCode(...bytes.subarray(at, at + 0x8000));
  return btoa(binary);
}

function numbered(record: Record<string, number>): string {
  return JSON.stringify(Object.entries(record).map(([code, value]) => [Number(code), value]));
}

// The pack's own values cross unscaled: `embedFont` is the one place that turns font units into the
// 1000-unit em a descriptor declares, and a second scale here would shrink every face above 1000 upem.
function faceLiteral(name: string, face: FontPackData["faces"][number], sfnt: Uint8Array): string {
  const { metrics } = face;
  return `  {
    name: ${JSON.stringify(name)},
    postScriptName: ${JSON.stringify(face.postScriptName)},
    sfnt: bytes(${JSON.stringify(base64(sfnt))}),
    glyphs: new Map(${numbered(metrics.glyphs)}),
    metrics: {
      unitsPerEm: ${metrics.unitsPerEm},
      ascent: ${metrics.ascent},
      descent: ${metrics.descent},
      bbox: ${JSON.stringify(metrics.bbox)},
      advances: new Map(${numbered(metrics.advances)}),
      kerning: new Map(${JSON.stringify(Object.entries(metrics.kerning))}),
    },
  }`;
}

/** The module a document imports its embedded faces from: the built subsets, inlined under the names they are selected by. @internal */
export function renderFacesModule(packs: readonly FontPackData[], sfnt: (path: string) => Uint8Array | undefined, emit: FontEmit): string {
  const names = new Set<string>();
  const literals: string[] = [];

  for (const [family, weights] of Object.entries(emit.faces)) {
    const pack = packs.find((candidate) => candidate.family === family);
    if (pack === undefined) throw new Error(`fonts.emit: no subset built for "${family}" — name it in fonts.subsets first`);
    for (const [weight, name] of Object.entries(weights)) {
      const face = pack.faces.find((candidate) => candidate.weight === Number(weight));
      if (face === undefined) throw new Error(`fonts.emit: no "${family}" subset at weight ${weight} — name it in fonts.subsets first`);
      const bytes = sfnt(face.sfnt);
      if (bytes === undefined) throw new Error(`fonts.emit: the "${family}" ${weight} subset at ${face.sfnt} has no bytes to inline`);
      names.add(name);
      literals.push(faceLiteral(name, face, bytes));
    }
  }

  for (const [base, name] of Object.entries(emit.defaults)) {
    if (!names.has(name)) throw new Error(`fonts.emit: defaults.${base} names "${name}", which no emitted face is called`);
  }

  const exported = emit.exports ?? DEFAULT_FACE_EXPORTS;
  return `${HEADER}
import type { PdfDefaultFaces, PdfEmbeddedFont } from "@y-core/forge/output/pdf";

function bytes(base64: string): Uint8Array {
  const binary = atob(base64);
  return Uint8Array.from(binary, (character) => character.charCodeAt(0));
}

/** The faces the document is embedded with, under the names its default pair selects on. */
export const ${exported.fonts}: readonly PdfEmbeddedFont[] = [
${literals.join(",\n")},
];

/** Which face sets each weight, so a heading is bold rather than the regular face emboldened. */
export const ${exported.defaults}: PdfDefaultFaces = ${JSON.stringify(emit.defaults, undefined, 2)};
`;
}
