import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, dirname, extname, join } from "node:path";

import { buildCursors } from "../../ui/assets/build/cursors";
import { copyAssets } from "./copy";
import { buildCSS } from "./css";
import { buildFonts } from "./fonts";
import { buildIcons } from "./icons";
import { buildJS } from "./js";
import { buildRasters } from "./rasters";
import { buildSite } from "./site";
import type { SpriteGroupResult } from "./sprites";
import { buildSprites } from "./sprites";
import type { ResolvedConfig } from "./types";

export interface BuildOptions {
  minify?: boolean;
  assetsPath?: string;
}

/** Runs every configured build step and writes the generated assets module; `minify` also enables content-hashed filenames. @public */
export async function buildAll(config: ResolvedConfig, opts?: BuildOptions): Promise<void> {
  const { publicDir, publicPrefix } = config.paths;
  const shouldHash = opts?.minify ?? false;
  mkdirSync(publicDir, { recursive: true });

  const manifest: Record<string, string> = {};
  let spriteGroups: Record<string, SpriteGroupResult> = {};
  let cursorBakes: Record<string, Record<string, string>> | undefined;

  const minifyOpts = opts?.minify !== undefined ? { minify: opts.minify } : {};

  for (const css of config.css) {
    const mapping = buildCSS(css, { outDir: publicDir, ...minifyOpts, hash: shouldHash });
    Object.assign(manifest, mapping);
  }

  copyAssets(config.copy, publicDir);

  await buildRasters(config.rasters, publicDir);

  if (Object.keys(config.sprites).length > 0) {
    const result = await buildSprites(config.sprites, publicDir, { hash: shouldHash });
    Object.assign(manifest, result.mapping);
    spriteGroups = result.groups;
  }

  if (config.fonts.downloads.length > 0) {
    await buildFonts(config.fonts, publicDir);
  }

  if (config.icons) {
    await buildIcons(config.icons);
  }

  if (config.site) {
    buildSite(config.site);
  }

  if (config.cursors) {
    const cssKey = config.cursors.css ?? config.css[0]?.output;
    const resolvedCss = cssKey !== undefined ? (manifest[cssKey] ?? cssKey) : undefined;
    if (resolvedCss) {
      const cssText = readFileSync(join(publicDir, resolvedCss), "utf-8");
      cursorBakes = buildCursors(config.cursors, cssText);
    }
  }

  const outputPath = opts?.assetsPath ?? DEFAULT_ASSETS_PATH;
  // esbuild resolves `@assets` while bundling, so the module must exist before `buildJS`.
  await generateAssetsModule(manifest, spriteGroups, publicPrefix, outputPath, cursorBakes);

  Object.assign(manifest, await buildJS(config.js.bundles, { outDir: publicDir, ...minifyOpts, hash: shouldHash }));

  await generateAssetsModule(manifest, spriteGroups, publicPrefix, outputPath, cursorBakes);

  emitHeaders(publicDir, publicPrefix, shouldHash);
}

/** Where the generated assets module is written when no path is stated. @internal */
export const DEFAULT_ASSETS_PATH = ".forge/assets.ts";

const BUILD_HEADER = "// AUTO-GENERATED by @y-core/forge assets build — do not edit.";

const TYPES_HEADER = [
  "// AUTO-GENERATED by `forge assets gen types` from assets.config.ts — do not edit.",
  "// TYPES ONLY: every path here is the unhashed logical name and every viewBox is empty.",
  "// Run `forge assets build all` before serving — this artifact is for typecheck and tests.",
].join("\n");

function toConstName(key: string): string {
  return `${key.replace(/[^a-zA-Z0-9]+/g, "_").toUpperCase()}_META`;
}

function toPascalCase(key: string): string {
  return key
    .split(/[^a-zA-Z0-9]+/)
    .map((seg) => (seg ? seg.charAt(0).toUpperCase() + seg.slice(1) : ""))
    .join("");
}

function renderAssetsModule(
  manifest: Record<string, string>,
  spriteGroups: Record<string, SpriteGroupResult>,
  publicPrefix: string,
  cursorBakes?: Record<string, Record<string, string>>,
  header: string = BUILD_HEADER,
): string {
  const dataEntries = Object.entries(manifest)
    .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`)
    .join("\n");

  const hasSprites = Object.keys(spriteGroups).length > 0;

  let content: string;

  if (hasSprites) {
    const groupBlocks = Object.entries(spriteGroups)
      .map(([key, group]) => {
        const constName = toConstName(key);
        const exportName = `${toPascalCase(key)}Icon`;
        const nameTypeName = `${toPascalCase(key)}IconName`;
        const metaEntries = Object.entries(group.meta)
          .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`)
          .join("\n");
        const glyphNames = Object.keys(group.meta).map((k) => (k.startsWith(group.prefix) ? k.slice(group.prefix.length) : k));
        const nameUnion = glyphNames.length > 0 ? glyphNames.map((n) => JSON.stringify(n)).join(" | ") : "never";
        return `const ${constName} = {\n${metaEntries}\n} as const;\n\nexport type ${nameTypeName} = ${nameUnion};\n\nexport const ${exportName} = createIcon(assets.path(${JSON.stringify(group.spriteKey)}), ${constName}, ${JSON.stringify(group.prefix)});`;
      })
      .join("\n\n");

    content = `${header}
import { createManifest } from "@y-core/forge/assets";
import { createIcon } from "@y-core/forge/ui/core";

const DATA: Record<string, string> = {
${dataEntries}
};

export const assets = createManifest(DATA, ${JSON.stringify(publicPrefix)});

${groupBlocks}
`;
  } else {
    content = `${header}
import { createManifest } from "@y-core/forge/assets";

const DATA: Record<string, string> = {
${dataEntries}
};

export const assets = createManifest(DATA, ${JSON.stringify(publicPrefix)});
`;
  }

  if (cursorBakes && Object.keys(cursorBakes).length > 0) {
    const cursorEntries = Object.entries(cursorBakes)
      .map(([cursor, themes]) => {
        const themeEntries = Object.entries(themes)
          .map(([theme, value]) => `    ${JSON.stringify(theme)}: ${JSON.stringify(value)},`)
          .join("\n");
        return `  ${JSON.stringify(cursor)}: {\n${themeEntries}\n  },`;
      })
      .join("\n");
    content += `\nexport const CURSOR_BAKES: Record<string, Record<string, string>> = {\n${cursorEntries}\n};\n`;
  }

  return content;
}

function writeAssetsModule(outputPath: string, content: string): void {
  if (existsSync(outputPath) && readFileSync(outputPath, "utf-8") === content) return;
  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, content);
}

async function generateAssetsModule(
  manifest: Record<string, string>,
  spriteGroups: Record<string, SpriteGroupResult>,
  publicPrefix: string,
  outputPath: string,
  cursorBakes?: Record<string, Record<string, string>>,
  header: string = BUILD_HEADER,
): Promise<void> {
  writeAssetsModule(outputPath, renderAssetsModule(manifest, spriteGroups, publicPrefix, cursorBakes, header));
}

/** The emitted module with every value blanked — the shape `ASSET_AND_BUILD_TOOLING.md` §6b holds the build and types artifacts to. @internal */
export function structuralSignature(module: string): string {
  const lines = module.split("\n");
  let start = 0;
  while (lines[start]?.startsWith("//")) start += 1;
  return lines
    .slice(start)
    .join("\n")
    .replace(/^(\s*"(?:[^"\\]|\\.)*":\s*)"(?:[^"\\]|\\.)*"(,)$/gm, "$1<value>$2");
}

const DATA_OPENING = "const DATA: Record<string, string> = {";

/** What an emitted assets module declares: whether it is the types-only artifact, and the path each
 *  logical name maps to — `null` when the module carries no `DATA` block at all. @internal */
export function readEmittedManifest(module: string): { typesOnly: boolean; data: Record<string, string> | null } {
  const typesOnly = module.startsWith(TYPES_HEADER);
  const start = module.indexOf(DATA_OPENING);
  if (start === -1) return { typesOnly, data: null };

  const bodyStart = start + DATA_OPENING.length;
  const data: Record<string, string> = {};
  for (const line of module.slice(bodyStart, module.indexOf("\n}", bodyStart)).split("\n")) {
    const match = line.match(/^\s*("(?:[^"\\]|\\.)*"):\s*("(?:[^"\\]|\\.)*"),$/);
    if (match?.[1] && match[2]) data[JSON.parse(match[1]) as string] = JSON.parse(match[2]) as string;
  }
  return { typesOnly, data };
}

function keepsExistingBuild(outputPath: string, typesContent: string): boolean {
  if (!existsSync(outputPath)) return false;
  const existing = readFileSync(outputPath, "utf-8");
  // An existing types artifact is rewritten as before — cheap, and byte-identical short-circuits.
  if (readEmittedManifest(existing).typesOnly) return false;
  return structuralSignature(existing) === structuralSignature(typesContent);
}

/** What `generateAssetsTypes` did to the module on disk. @public */
export type AssetsTypesOutcome = "written" | "kept-build-artifact";

/** Writes the generated assets module from `assets.config.ts` alone, with placeholder values, unless an existing build artifact still fits the config. @public */
export async function generateAssetsTypes(config: ResolvedConfig, opts?: { assetsPath?: string }): Promise<AssetsTypesOutcome> {
  const manifest: Record<string, string> = {};

  for (const css of config.css) {
    manifest[css.output] = css.output;
  }

  const spriteGroups: Record<string, SpriteGroupResult> = {};
  for (const [key, group] of Object.entries(config.sprites)) {
    manifest[group.target] = group.target;

    const prefix = group.prefix ?? "icon-";
    const meta: Record<string, string> = {};
    for (const source of group.sources) {
      for (const rawEntry of source.files) {
        const symbolKey = typeof rawEntry === "string" ? basename(rawEntry, ".svg") : rawEntry.key;
        meta[`${prefix}${symbolKey}`] = "";
      }
    }
    spriteGroups[key] = { spriteKey: group.target, meta, prefix };
  }

  for (const bundle of config.js.bundles) {
    const logicalName = `${bundle.outdir}/${basename(bundle.entry, extname(bundle.entry))}.js`;
    manifest[logicalName] = logicalName;
  }

  let cursorBakes: Record<string, Record<string, string>> | undefined;
  const cursors = config.cursors;
  if (cursors) {
    cursorBakes = {};
    const themes = Object.keys(cursors.themes);
    for (const source of cursors.sources) {
      for (const rawEntry of source.files) {
        const cursorKey = typeof rawEntry === "string" ? rawEntry.replace(/\.svg$/, "") : rawEntry.key;
        const perTheme: Record<string, string> = {};
        for (const theme of themes) perTheme[theme] = "";
        cursorBakes[cursorKey] = perTheme;
      }
    }
  }

  const outputPath = opts?.assetsPath ?? DEFAULT_ASSETS_PATH;
  const content = renderAssetsModule(manifest, spriteGroups, config.paths.publicPrefix, cursorBakes, TYPES_HEADER);
  if (keepsExistingBuild(outputPath, content)) return "kept-build-artifact";
  writeAssetsModule(outputPath, content);
  return "written";
}

function emitHeaders(publicDir: string, publicPrefix: string, hashed: boolean): void {
  const headersPath = join(dirname(publicDir), "_headers");
  const cacheControl = hashed ? "public, max-age=31536000, immutable" : "no-cache";
  // Same normalization `createManifest` applies, so the rule cannot disagree with the served URL.
  const base = publicPrefix.endsWith("/") ? publicPrefix.slice(0, -1) : publicPrefix;
  const content = `${base}/*\n  Cache-Control: ${cacheControl}\n`;
  writeFileSync(headersPath, content);
}
