import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import process, { env } from "node:process";
import { createInterface } from "node:readline/promises";

import { createCommand } from "../../cli/command";
import { CliError } from "../../cli/errors";
import { splitList } from "../../cli/parse";
import type { CliContext } from "../../cli/types";
import type { Colorize } from "../../term/color";
import { PLAIN } from "../../term/color";
import { loadWranglerConfig, writeWranglerConfig } from "../config/parse";
import type { TableOptions } from "../table";
import { renderSections } from "../table";
import type { DeploymentTarget } from "../target";
import { describeTarget, detectTarget } from "../target";
import type { CfAuth, PrefixStrategy, ResolvedPrefix, ResourceType, SyncAction, SyncNote, SyncOutput, SyncResult } from "../types";
import { ACTION_LABELS, RESOURCE_TYPES } from "../types";
import { syncBindings } from "./engine";
import { devVarsPath, GENERATE_MARKER, PUSH_MARKER, readDevVars } from "./handlers/devvars";
import { buildHandlers } from "./handlers/registry";
import { describeRefusal, planRotation, rotateSecrets } from "./handlers/rotate";

/** The one `--rotate` argument that is not a key name. */
const ROTATE_ALL = "all";

/** The flags of `cf sync`, which reports by default and changes nothing without `--commit`. */
const syncFlags = {
  config: { type: "string" as const, short: "c", description: "Path to wrangler.jsonc", default: "wrangler.jsonc" },
  commit: {
    type: "boolean" as const,
    description:
      "Apply changes: create missing remote resources and write resolved IDs back into the config. Without this flag nothing is written anywhere",
  },
  force: {
    type: "boolean" as const,
    description:
      "With --commit, permit a whole-file JSON rewrite when comments cannot be preserved. Destroys comments; the run reports what it lost",
  },
  prefix: { type: "string" as const, description: "Custom prefix for remote resource names" },
  "no-prefix": { type: "boolean" as const, description: "Disable prefixing (use binding name as-is)" },
  resources: {
    type: "string" as const,
    short: "r",
    multiple: true as const,
    description: "Categories (local, deploy, commit, rotate) or exact resource types to sync. Repeatable, and comma-separated lists are accepted",
  },
  rotate: {
    type: "string" as const,
    multiple: true as const,
    description: `Replace secrets that already exist remotely: named one per flag or comma-separated, or "${ROTATE_ALL}" for every key marked "${GENERATE_MARKER}". A marked secret that is not there yet is generated by --commit alone`,
  },
  local: {
    type: "boolean" as const,
    description: "With --rotate, regenerate the values in .dev.vars only. Touches no Cloudflare API and needs no credentials",
  },
  yes: {
    type: "boolean" as const,
    description: "Skip the confirmation --rotate asks before destroying a value that is already in use. Required in a non-interactive run",
  },
  check: {
    type: "boolean" as const,
    description: "Exit non-zero when anything is out of step — pending creates, rotations, drift, or names only the remote has. For CI",
  },
  json: { type: "boolean" as const, description: "Print the run as a JSON document instead of a table. The only thing written to stdout" },
  "account-id": { type: "string" as const, description: "Cloudflare account ID (or CLOUDFLARE_ACCOUNT_ID env)" },
  "api-token": { type: "string" as const, description: "Cloudflare API token (or CLOUDFLARE_API_TOKEN env)" },
};

function resolveAuth(flags: Record<string, string | string[] | boolean | undefined>): CfAuth {
  const accountId = (flags["account-id"] as string | undefined) ?? env.CLOUDFLARE_ACCOUNT_ID;
  const apiToken = (flags["api-token"] as string | undefined) ?? env.CLOUDFLARE_API_TOKEN;

  if (!accountId) throw new CliError("invalid-args", "Missing account ID. Set --account-id or CLOUDFLARE_ACCOUNT_ID");
  if (!apiToken)
    throw new CliError(
      "invalid-args",
      "Missing API token. Set --api-token or CLOUDFLARE_API_TOKEN; https://dash.cloudflare.com/profile/api-tokens",
    );

  return { accountId, apiToken };
}

/** The `--resources` categories that name more than one section. */
const COMPOUND_ALIASES: Record<string, readonly string[]> = { commit: ["secrets", "provision"] };

function aliasMap(): Map<string, ResourceType[]> {
  const bySection = new Map(SECTIONS.map((spec) => [spec.alias, typesFor(spec)]));
  const resolved = new Map(bySection);
  for (const [name, parts] of Object.entries(COMPOUND_ALIASES)) {
    resolved.set(
      name,
      parts.flatMap((part) => bySection.get(part) ?? []),
    );
  }
  return resolved;
}

function resourceVocabulary(): string {
  const categories = [...SECTIONS.map((s) => s.alias), ...Object.keys(COMPOUND_ALIASES)];
  return `categories: ${categories.join(", ")}; types: ${RESOURCE_TYPES.join(", ")}`;
}

/** Parses `--resources` into resource types, accepting a category name and rejecting unknown ones. */
export function parseResources(raw: string | readonly string[] | undefined): ResourceType[] | undefined {
  // An empty array is a repeatable flag's absence; `--resources ","` arrives as `[","]` and is
  // still refused as empty.
  if (raw === undefined || (Array.isArray(raw) && raw.length === 0)) return undefined;

  const requested = splitList(raw);
  if (requested.length === 0) {
    throw new CliError("invalid-args", `--resources was empty. Valid ${resourceVocabulary()}`);
  }

  const known = new Set<string>(RESOURCE_TYPES);
  const byAlias = aliasMap();

  const unknown = requested.filter((r) => !known.has(r) && !byAlias.has(r));
  if (unknown.length > 0) {
    throw new CliError("invalid-args", `Unknown resource${unknown.length > 1 ? "s" : ""}: ${unknown.join(", ")}. Valid ${resourceVocabulary()}`);
  }

  // Deduped: `-r commit,secrets` names `secrets` twice, and the engine's filter would then run
  // that handler twice.
  return [...new Set(requested.flatMap((r) => byAlias.get(r) ?? [r as ResourceType]))];
}

/** Parses `--rotate` and checks every name against the markers in `.dev.vars` before any request. */
export function resolveRotation(raw: string | readonly string[] | undefined, configPath: string): string[] {
  if (raw === undefined || (Array.isArray(raw) && raw.length === 0)) return [];

  const names = splitList(raw);
  const path = devVarsPath(configPath);
  if (names.length === 0) {
    throw new CliError("invalid-args", `--rotate was empty. Name the secrets to regenerate, or "${ROTATE_ALL}", as declared in ${path}`);
  }

  const devVars = readDevVars(path);

  if (names.includes(ROTATE_ALL)) {
    const rotatable = devVars.filter((v) => v.kind === "rotatable").map((v) => v.name);
    if (rotatable.length === 0) {
      throw new CliError("invalid-args", `--rotate ${ROTATE_ALL} found no keys marked "${GENERATE_MARKER}" in ${path}`);
    }
    return rotatable;
  }

  const plan = planRotation(devVars, names);
  if (!plan.ok) throw new CliError("invalid-args", describeRefusal(plan.error, path));
  return plan.data;
}

/** Runs `--local --rotate`: replaces development values in `.dev.vars` and stops. */
async function runLocalRotate(flags: LooseFlags, commit: boolean): Promise<void> {
  const configPath = (flags.config as string) ?? "wrangler.jsonc";
  const path = devVarsPath(configPath);
  const names = resolveRotation(flags.rotate as string[] | undefined, configPath);

  if (!commit) {
    console.log(`Would rotate in ${path}: ${names.join(", ")}`);
    console.log("\n(status only — nothing was written. Re-run with --commit to apply.)");
    return;
  }

  await confirmRotation(names, path, flags);
  rotateSecrets(path, names);
  console.log(`Rotated in ${path}: ${names.join(", ")}`);
  console.log(
    "New values were written to the file and are not printed. Cloudflare is unchanged — rotate there with --commit --rotate, without --local.",
  );
}

/** Asks before replacing secrets that are already in use, refusing a non-interactive run. */
async function confirmRotation(names: string[], where: string, flags: LooseFlags): Promise<void> {
  if (names.length === 0 || flags.yes) return;

  const what = `${names.length} secret${names.length === 1 ? "" : "s"} on ${where}`;
  if (!process.stdin.isTTY) {
    throw new CliError(
      "invalid-args",
      `Refusing to rotate ${what} without a terminal to confirm at: ${names.join(", ")}.\nThe old values cannot be recovered. Pass --yes to say so deliberately.`,
    );
  }

  console.log(`About to replace ${what}: ${names.join(", ")}`);
  console.log("The current values are destroyed and cannot be recovered.");

  const rl = createInterface({ input: process.stdin, output: process.stdout });
  try {
    const answer = await rl.question("Continue? [y/N] ");
    if (answer.trim().toLowerCase() !== "y") throw new CliError("invalid-args", "Rotation cancelled; nothing was written.");
  } finally {
    rl.close();
  }
}

function resolvePrefixStrategy(flags: Record<string, unknown>): PrefixStrategy {
  if (flags["no-prefix"]) return { kind: "none" };
  if (flags.prefix) return { kind: "custom", prefix: flags.prefix as string };
  return { kind: "project-name" };
}

/** One section of the report, grouping rows by the actor that changes them. */
interface SectionSpec {
  title: string;
  /** The word `--resources` accepts for this whole category. */
  alias: string;
  note: string | ((prefix: ResolvedPrefix) => string);
  /** Absent means "everything no other section claimed". */
  types?: ResourceType[];
  presence?: boolean;
  withType?: boolean;
}

const SECTIONS: SectionSpec[] = [
  {
    title: "Local Only",
    alias: "local",
    note: `.dev.vars declared keys with no marker and no matching vars in wrangler.jsonc`,
    types: ["local_vars"],
    presence: false,
  },
  {
    // The catch-all sits here rather than last: a binding this tool does not yet know about is
    // bound by the deploy, so that is the safe default section for a new one.
    title: "Pushed by the Next Deploy",
    alias: "deploy",
    note: "wrangler.jsonc declared keys; `deploy` writes them, sync only reports",
    withType: true,
  },
  {
    title: "Created by --commit",
    alias: "secrets",
    note: `.dev.vars secrets marked '${PUSH_MARKER}', created remotely under their own name`,
    types: ["secrets"],
  },
  {
    title: "Provisioned by --commit",
    alias: "provision",
    note: (prefix) => `Bindings created as ${prefix ? `${prefix}_<BINDING>` : "<BINDING>"} with the id written back into wrangler.jsonc`,
    types: ["kv_namespaces", "d1_databases", "r2_buckets", "queues"],
    withType: true,
  },
  {
    title: "Rotated by --commit",
    alias: "rotate",
    note: `.dev.vars keys marked '${GENERATE_MARKER}'; --commit generates remote secret; --rotate rotates secrets`,
    types: ["rotatable_secrets"],
  },
];

/** The resource types one section covers, with the catch-all taking whatever no section claimed. */
function typesFor(spec: SectionSpec): ResourceType[] {
  if (spec.types) return spec.types;
  const claimed = new Set(SECTIONS.flatMap((s) => s.types ?? []));
  return RESOURCE_TYPES.filter((t) => !claimed.has(t));
}

/** Renders a sync action's label in the colour its outcome class is shown in. @public */
export function styleAction(action: SyncAction, style: Colorize): string {
  const label = ACTION_LABELS[action];
  switch (action) {
    case "created":
    case "updated":
    case "rotated":
    case "in-sync":
      return style.green(label);
    case "would-create":
    case "would-rotate":
      return style.cyan(label);
    case "drift":
    case "remote-only":
    case "unavailable":
      return style.yellow(label);
    case "error":
      return style.red(label);
    default:
      return style.dim(label);
  }
}

/** `yes` / `no` for a side that was checked, blank for one that was not. */
const presenceCell = (known: boolean | undefined) => (known === undefined ? "" : known ? "yes" : "no");

/** Builds the printable rows for one section, dropping columns that would say nothing. */
function sectionRows(results: SyncResult[], spec: SectionSpec, strip: (detail: string) => string, style: Colorize) {
  const named = results.some((r) => r.remoteName !== undefined && r.remoteName !== r.binding);
  const presence = spec.presence !== false;

  return results.map((r) => ({
    ...(spec.withType ? { Type: r.resourceType } : {}),
    Binding: r.binding,
    ...(named ? { "Remote Name": r.remoteName ?? "" } : {}),
    ...(presence ? { Local: presenceCell(r.local), Remote: presenceCell(r.remote) } : {}),
    Action: styleAction(r.action, style),
    "Remote ID": r.remoteId ?? "",
    Detail: strip(r.detail ?? ""),
  }));
}

/** The rows a reader would act on: neither settled nor left unqueried. */
export function pendingRows(results: SyncResult[]): SyncResult[] {
  const settled = new Set<SyncResult["action"]>(["in-sync", "local-only", "created", "updated", "rotated"]);
  return results.filter((r) => !settled.has(r.action) && r.remote !== undefined);
}

export function summariseCommit(results: SyncResult[]): string {
  const count = (action: SyncResult["action"]) => results.filter((r) => r.action === action).length;
  const parts = [[count("would-create"), "create"] as const, [count("would-rotate"), "rotate"] as const]
    .filter(([n]) => n > 0)
    .map(([n, verb]) => `${verb} ${n}`);

  if (parts.length === 0) return "(status only — nothing was written, and --commit would change nothing here.)";
  return `(status only — nothing was written. --commit would ${parts.join(" and ")}. Re-run with --commit to apply.)`;
}

export function printResults(
  results: SyncResult[],
  target: DeploymentTarget,
  prefix: ResolvedPrefix = "",
  notes: SyncNote[] = [],
  options: TableOptions = {},
): void {
  const style = options.style ?? PLAIN;
  if (results.length === 0 && notes.length === 0) {
    console.log("No bindings found.");
    return;
  }

  // `SyncResult.detail` stays self-describing for programmatic callers, so the surface prefix is
  // stripped here rather than omitted there.
  const surface = `${describeTarget(target)} · `;
  const strip = (detail: string) => (detail.startsWith(surface) ? detail.slice(surface.length) : detail);

  const sections = SECTIONS.map((spec) => {
    const types = new Set(typesFor(spec));
    return {
      title: spec.title,
      note: typeof spec.note === "function" ? spec.note(prefix) : spec.note,
      rows: sectionRows(
        results.filter((r) => types.has(r.resourceType)),
        spec,
        strip,
        style,
      ),
      footers: notes.filter((n) => types.has(n.resourceType)).map((n) => n.message),
    };
  });

  console.log(`${style.bold(`${describeTarget(target)} · ${target.name}`)}\n`);
  // `Action` and `Detail` are prose and may wrap; every other column is an identifier, which
  // truncates legibly but is no longer searchable once broken across two lines.
  console.log(renderSections(sections, { ...options, style, wrap: ["Action", "Detail"] }));
}

type LooseFlags = Record<string, string | string[] | boolean | undefined>;

/** What `--json` prints: the whole run, in the vocabulary the types already define. */
interface JsonReport {
  target: SyncOutput["target"];
  prefix: ResolvedPrefix;
  committed: boolean;
  results: SyncResult[];
  notes: SyncNote[];
  pending: number;
  configWrite?: { path: string; edits: number; rewritten: boolean };
}

// `--rotate` is repeatable, so its absence is an empty array — truthy — and every guard asking
// "was it given?" has to ask about length.
function given(value: LooseFlags[string]): boolean {
  return Array.isArray(value) ? value.length > 0 : value !== undefined && value !== false;
}

async function runSync(flags: LooseFlags, ctx?: CliContext): Promise<void> {
  const commit = Boolean(flags.commit);
  if (!commit && flags.force) {
    throw new CliError("invalid-args", "--force only means something alongside --commit, which is what permits a write.");
  }
  if (commit && flags.check) {
    throw new CliError(
      "invalid-args",
      "--check asks whether anything is pending; --commit applies it. Asking for both is asking whether the change you just made was needed.",
    );
  }
  if (flags.local && !given(flags.rotate)) {
    throw new CliError("invalid-args", "--local only means something alongside --rotate: it is where a rotation writes, not a mode of its own.");
  }
  if (flags.local) return runLocalRotate(flags, commit);

  const auth = resolveAuth(flags);
  const configPath = (flags.config as string) ?? "wrangler.jsonc";
  const json = Boolean(flags.json);
  // `--json` selects PLAIN before anything is rendered: the payload is data, and no escape
  // sequence may reach a caller parsing stdout.
  const style = json ? PLAIN : (ctx?.out ?? PLAIN);

  const resources = parseResources(flags.resources as string[] | undefined);
  const rotate = resolveRotation(flags.rotate as string[] | undefined, configPath);
  // Loaded once, with its source text, so write-back splices offsets computed from
  // bytes it actually validated rather than from a re-read after the API round-trip.
  const loaded = loadWranglerConfig(configPath);

  // Before the first request, not after: a confirmation that arrives once half the
  // secrets are already replaced is not a confirmation.
  if (commit) {
    const target = detectTarget(loaded.config, loaded.config.name);
    await confirmRotation(rotate, `${describeTarget(target)} ${target.name}`, flags);
  }

  const output = await syncBindings(
    loaded.config,
    // `dryRun` is the engine's word for the same switch: without --commit, handlers
    // read but never write.
    { auth, dryRun: !commit, prefix: resolvePrefixStrategy(flags), resources, rotate },
    // Rebuilt per invocation so that handlers needing the resolved --config path
    // — secrets, which finds .dev.vars beside it — actually receive it.
    buildHandlers({ configPath }),
  );

  const report: JsonReport = {
    target: output.target,
    prefix: output.prefix,
    committed: commit,
    results: output.results,
    notes: output.notes,
    pending: pendingRows(output.results).length,
  };

  // Absent a context — a direct programmatic call — no width is imposed and the grid is as wide
  // as its content.
  if (!json)
    printResults(output.results, output.target, output.prefix, output.notes, { style, ...(ctx === undefined ? {} : { width: ctx.width }) });

  if (!json) {
    const untouched = describeUntouchedZone(process.cwd());
    if (untouched !== null) console.log(`\n${style.dim(untouched)}`);
  }

  if (!commit) {
    if (!json) console.log(`\n${summariseCommit(output.results)}`);
  } else if (output.configChanged) {
    const write = writeWranglerConfig(loaded, output.updatedConfig, { force: Boolean(flags.force) });
    if (!write.ok) throw write.error;

    report.configWrite = { path: write.data.path, edits: write.data.edits, rewritten: Boolean(write.data.lost) };

    if (json) {
      // Nothing but the document reaches stdout, or the caller has to parse around it.
    } else if (write.data.lost) {
      // The one destructive outcome `forge sync` has: comments and formatting are gone and cannot
      // be recovered from the file. It is yellow because it is a warning, not a report.
      const { comments, unsupported } = write.data.lost;
      console.log(`\n${style.yellow(`Rewrote ${write.data.path} as plain JSON (--force).`)}`);
      console.log(`  lost: ${comments} comment${comments === 1 ? "" : "s"} and all original formatting`);
      console.log(`  changes that could not be spliced: ${unsupported.join(", ")}`);
    } else if (write.data.written) {
      console.log(
        `\n${style.green(`Updated ${write.data.path}`)} — ${write.data.edits} value${write.data.edits === 1 ? "" : "s"} spliced in; every other byte is unchanged.`,
      );
    }
  }

  if (json) console.log(JSON.stringify(report, null, 2));

  // Signalled without returning early: an `error` row must not suppress the
  // write-back of the rows that did resolve.
  if (output.results.some((r) => r.action === "error")) process.exitCode = 1;
  else if (flags.check && report.pending > 0) process.exitCode = 1;
}

/** Description shared by `cf sync` and `cf sync account`, which are the same command. @internal */
export const SYNC_ACCOUNT_DESCRIPTION =
  "Compare the account's bindings, vars and secrets against the remote and report on them. Read-only unless --commit, which creates the missing resources and writes resolved IDs back into the config";

/** Flags shared by `cf sync` and `cf sync account`. @internal */
export const syncAccountFlags = syncFlags;

/** Runs an account-scope reconciliation. Shared by the bare `cf sync` and by `cf sync account`. @internal */
export function runSyncAccount(flags: LooseFlags, ctx?: CliContext): Promise<void> {
  return runSync(flags, ctx);
}

/** Names the zone scope a defaulted account run did not touch, or null when none is declared. @internal */
export function describeUntouchedZone(root: string, siteConfigPath = "config/site.ts"): string | null {
  const path = resolve(root, siteConfigPath);
  if (!existsSync(path)) return null;
  // A textual probe, not an import: loading the site config would execute the app's route table to
  // answer a question about whether a file mentions a zone.
  if (!/\bzone\s*:/.test(readFileSync(path, "utf-8"))) return null;
  return `${siteConfigPath} declares zone rules, which this run did not touch — reconcile them with \`forge cf sync zone\`.`;
}

/** The `forge cf sync account` subcommand. @public */
export function createSyncAccountCommand() {
  return createCommand({
    name: "account",
    description: SYNC_ACCOUNT_DESCRIPTION,
    flags: syncAccountFlags,
    run: (_args, flags, ctx) => runSyncAccount(flags as LooseFlags, ctx),
  });
}
