import process, { env } from "node:process";
import { createInterface } from "node:readline/promises";
import { createCommand } from "../core/command";
import { CliError } from "../core/errors";
import { splitList } from "../core/parse";
import type { CliContext } from "../core/types";
import type { Colorize } from "../term/color";
import { PLAIN } from "../term/color";
import { loadWranglerConfig, writeWranglerConfig } from "./config/parse";
import { syncBindings } from "./engine";
import { devVarsPath, GENERATE_MARKER, PUSH_MARKER, readDevVars } from "./handlers/devvars";
import { buildHandlers } from "./handlers/registry";
import { describeRefusal, planRotation, rotateSecrets } from "./handlers/rotate";
import type { TableOptions } from "./table";
import { renderSections } from "./table";
import type { DeploymentTarget } from "./target";
import { describeTarget, detectTarget } from "./target";
import type { CfAuth, PrefixStrategy, ResolvedPrefix, ResourceType, SyncAction, SyncNote, SyncOutput, SyncResult } from "./types";
import { ACTION_LABELS, RESOURCE_TYPES } from "./types";

/**
 * The one `--rotate` argument that is not a key name.
 *
 * Lower-case deliberately: `.dev.vars` keys are conventionally `UPPER_SNAKE`, so a
 * literal `all` is the spelling least likely to collide with one.
 */
const ROTATE_ALL = "all";

/**
 * One command, two modes.
 *
 * `sync` reports status by default — it performs only the reads needed to compare
 * local bindings against the remote, and prints the plan. `--commit` is the one
 * flag that permits any change at all, to Cloudflare or to the working tree.
 *
 * There is deliberately no separate `status` command and no `--dry-run`: both were
 * spellings of the default, and a second way to say "do nothing" is a second thing
 * to keep honest.
 */
const syncFlags = {
  config: { type: "string" as const, short: "c", description: "Path to wrangler.jsonc", default: "wrangler.jsonc" },
  commit: {
    type: "boolean" as const,
    description:
      "Apply changes: create missing remote resources and write resolved IDs back into the config. Without this flag nothing is written anywhere",
  },
  force: {
    type: "boolean" as const,
    description:
      "With --commit, permit a whole-file JSON rewrite when comments cannot be preserved. Destroys comments; the run reports what it lost",
  },
  prefix: { type: "string" as const, description: "Custom prefix for remote resource names" },
  "no-prefix": { type: "boolean" as const, description: "Disable prefixing (use binding name as-is)" },
  resources: {
    type: "string" as const,
    short: "r",
    multiple: true as const,
    description: "Categories (local, deploy, commit, rotate) or exact resource types to sync. Repeatable, and comma-separated lists are accepted",
  },
  rotate: {
    type: "string" as const,
    multiple: true as const,
    description: `Replace secrets that already exist remotely: named one per flag or comma-separated, or "${ROTATE_ALL}" for every key marked "${GENERATE_MARKER}". A marked secret that is not there yet is generated by --commit alone`,
  },
  local: {
    type: "boolean" as const,
    description: "With --rotate, regenerate the values in .dev.vars only. Touches no Cloudflare API and needs no credentials",
  },
  yes: {
    type: "boolean" as const,
    description: "Skip the confirmation --rotate asks before destroying a value that is already in use. Required in a non-interactive run",
  },
  check: {
    type: "boolean" as const,
    description: "Exit non-zero when anything is out of step — pending creates, rotations, drift, or names only the remote has. For CI",
  },
  json: { type: "boolean" as const, description: "Print the run as a JSON document instead of a table. The only thing written to stdout" },
  "account-id": { type: "string" as const, description: "Cloudflare account ID (or CLOUDFLARE_ACCOUNT_ID env)" },
  "api-token": { type: "string" as const, description: "Cloudflare API token (or CLOUDFLARE_API_TOKEN env)" },
};

function resolveAuth(flags: Record<string, string | string[] | boolean | undefined>): CfAuth {
  const accountId = (flags["account-id"] as string | undefined) ?? env.CLOUDFLARE_ACCOUNT_ID;
  const apiToken = (flags["api-token"] as string | undefined) ?? env.CLOUDFLARE_API_TOKEN;

  if (!accountId) throw new CliError("invalid-args", "Missing account ID. Set --account-id or CLOUDFLARE_ACCOUNT_ID");
  if (!apiToken)
    throw new CliError(
      "invalid-args",
      "Missing API token. Set --api-token or CLOUDFLARE_API_TOKEN; https://dash.cloudflare.com/profile/api-tokens",
    );

  return { accountId, apiToken };
}

/** What `--resources` accepts beyond an exact type name, listed for its error message. */
/**
 * Categories that name more than one section.
 *
 * `commit` covered both halves of `--commit` before the report split them, and a token that has
 * been in scripts and documentation does not stop meaning what it meant because the *display*
 * gained a heading. Derived from the sections rather than listed, so it cannot drift from them.
 */
const COMPOUND_ALIASES: Record<string, readonly string[]> = { commit: ["secrets", "provision"] };

function aliasMap(): Map<string, ResourceType[]> {
  const bySection = new Map(SECTIONS.map((spec) => [spec.alias, typesFor(spec)]));
  const resolved = new Map(bySection);
  for (const [name, parts] of Object.entries(COMPOUND_ALIASES)) {
    resolved.set(
      name,
      parts.flatMap((part) => bySection.get(part) ?? []),
    );
  }
  return resolved;
}

function resourceVocabulary(): string {
  const categories = [...SECTIONS.map((s) => s.alias), ...Object.keys(COMPOUND_ALIASES)];
  return `categories: ${categories.join(", ")}; types: ${RESOURCE_TYPES.join(", ")}`;
}

/**
 * Parse `--resources`, rejecting unknown names.
 *
 * Accepts either an exact resource type or a **category** — the same four words the
 * report groups by. `-r secrets` selecting only the fixed ones was a papercut with no
 * good answer at the type level: fixed and generated secrets are genuinely different
 * types, and the word a reader reaches for names the category, not the type.
 *
 * Names are validated rather than cast, because a value cast straight to
 * `ResourceType` is then silently dropped by the engine's filter — `-r ratelimit`
 * printed "No bindings found.", a typo rendered as a fact about the account.
 */
export function parseResources(raw: string | readonly string[] | undefined): ResourceType[] | undefined {
  // An empty array is the flag's absence — what a repeatable flag resolves to when it was never
  // given. `--resources ","` still arrives as `[","]` and is still refused as empty.
  if (raw === undefined || (Array.isArray(raw) && raw.length === 0)) return undefined;

  const requested = splitList(raw);
  if (requested.length === 0) {
    throw new CliError("invalid-args", `--resources was empty. Valid ${resourceVocabulary()}`);
  }

  const known = new Set<string>(RESOURCE_TYPES);
  const byAlias = aliasMap();

  const unknown = requested.filter((r) => !known.has(r) && !byAlias.has(r));
  if (unknown.length > 0) {
    throw new CliError("invalid-args", `Unknown resource${unknown.length > 1 ? "s" : ""}: ${unknown.join(", ")}. Valid ${resourceVocabulary()}`);
  }

  // Deduped, because `-r commit,secrets` names `secrets` twice and the engine's
  // filter would then run that handler twice.
  return [...new Set(requested.flatMap((r) => byAlias.get(r) ?? [r as ResourceType]))];
}

/**
 * Parse `--rotate` and check every name against the markers in `.dev.vars`.
 *
 * The check happens before any request, so a run that names an unrotatable secret
 * stops having done nothing at all — rather than pushing the rest and then failing
 * on the one key that could not be replaced.
 *
 * `--rotate` is only needed to replace a value that is **already** on the remote. A
 * rotatable secret that is not there yet is generated by a plain `--commit`, so this
 * flag never has to be remembered for a first run.
 */
export function resolveRotation(raw: string | readonly string[] | undefined, configPath: string): string[] {
  if (raw === undefined || (Array.isArray(raw) && raw.length === 0)) return [];

  const names = splitList(raw);
  const path = devVarsPath(configPath);
  if (names.length === 0) {
    throw new CliError("invalid-args", `--rotate was empty. Name the secrets to regenerate, or "${ROTATE_ALL}", as declared in ${path}`);
  }

  const devVars = readDevVars(path);

  if (names.includes(ROTATE_ALL)) {
    const rotatable = devVars.filter((v) => v.kind === "rotatable").map((v) => v.name);
    if (rotatable.length === 0) {
      throw new CliError("invalid-args", `--rotate ${ROTATE_ALL} found no keys marked "${GENERATE_MARKER}" in ${path}`);
    }
    return rotatable;
  }

  const plan = planRotation(devVars, names);
  if (!plan.ok) throw new CliError("invalid-args", describeRefusal(plan, path));
  return plan.names;
}

/**
 * `--local --rotate` — replace development values in `.dev.vars` and stop.
 *
 * Separate from the remote rotation because the two are separate acts: a remote
 * secret is never copied onto this machine, so the local and remote values of one
 * name are expected to differ.
 */
async function runLocalRotate(flags: LooseFlags, commit: boolean): Promise<void> {
  const configPath = (flags.config as string) ?? "wrangler.jsonc";
  const path = devVarsPath(configPath);
  const names = resolveRotation(flags.rotate as string[] | undefined, configPath);

  if (!commit) {
    console.log(`Would rotate in ${path}: ${names.join(", ")}`);
    console.log("\n(status only — nothing was written. Re-run with --commit to apply.)");
    return;
  }

  await confirmRotation(names, path, flags);
  rotateSecrets(path, names);
  console.log(`Rotated in ${path}: ${names.join(", ")}`);
  console.log(
    "New values were written to the file and are not printed. Cloudflare is unchanged — rotate there with --commit --rotate, without --local.",
  );
}

/**
 * Ask before replacing secrets that are already in use.
 *
 * The marker in `.dev.vars` is the opt-in for whether a key may *ever* be generated;
 * it says nothing about whether this run should do it now. `--rotate all --commit` is
 * one keystroke away from replacing every live production secret, and the old values
 * cannot be recovered — so the count and the names are read back before anything is
 * written.
 *
 * **A non-interactive run refuses rather than proceeding.** Silence from a pipe is
 * not consent, and a CI job that meant it can say so with `--yes`.
 */
async function confirmRotation(names: string[], where: string, flags: LooseFlags): Promise<void> {
  if (names.length === 0 || flags.yes) return;

  const what = `${names.length} secret${names.length === 1 ? "" : "s"} on ${where}`;
  if (!process.stdin.isTTY) {
    throw new CliError(
      "invalid-args",
      `Refusing to rotate ${what} without a terminal to confirm at: ${names.join(", ")}.\nThe old values cannot be recovered. Pass --yes to say so deliberately.`,
    );
  }

  console.log(`About to replace ${what}: ${names.join(", ")}`);
  console.log("The current values are destroyed and cannot be recovered.");

  const rl = createInterface({ input: process.stdin, output: process.stdout });
  try {
    const answer = await rl.question("Continue? [y/N] ");
    if (answer.trim().toLowerCase() !== "y") throw new CliError("invalid-args", "Rotation cancelled; nothing was written.");
  } finally {
    rl.close();
  }
}

function resolvePrefixStrategy(flags: Record<string, unknown>): PrefixStrategy {
  if (flags["no-prefix"]) return { kind: "none" };
  if (flags.prefix) return { kind: "custom", prefix: flags.prefix as string };
  return { kind: "project-name" };
}

/**
 * The report's shape: **one section per actor.**
 *
 * A reader arrives with one question — *what happens to this name, and who does it?*
 * — and there are only four answers: nothing does, the next deploy does, `--commit`
 * creates it, `--commit` generates it. Grouping by that rather than by resource kind
 * is what lets each rule be stated once, in a heading, instead of repeated down a
 * `Detail` column; the `Type` column carries the resource kind where a section holds
 * more than one.
 *
 * `presence` is off for Local Only, where both columns would be constant: the
 * heading already says these never go anywhere.
 */
interface SectionSpec {
  title: string;
  /** The word `--resources` accepts for this whole category. */
  alias: string;
  note: string | ((prefix: ResolvedPrefix) => string);
  /** Absent means "everything no other section claimed". */
  types?: ResourceType[];
  presence?: boolean;
  withType?: boolean;
}

const SECTIONS: SectionSpec[] = [
  {
    title: "Local Only",
    alias: "local",
    note: `.dev.vars declared keys with no marker and no matching vars in wrangler.jsonc`,
    types: ["local_vars"],
    presence: false,
  },
  {
    // The catch-all sits here rather than last: a declarative binding this tool does
    // not yet know about is bound by the deploy, so that is where a new one belongs
    // by default, and the default is the safe answer.
    title: "Pushed by the Next Deploy",
    alias: "deploy",
    note: "wrangler.jsonc declared keys; `deploy` writes them, sync only reports",
    withType: true,
  },
  // Two sections, because `--commit` does two different things and one note could not state both.
  // **A secret is not a binding.** It has no id, takes no prefix, and is created under its own
  // name: it either exists remotely or it does not. KV, D1, R2 and queues are resources created
  // independently and then linked, which is what the prefix and the id write-back are for. Run
  // together they shared a table whose `Remote Name` column merely repeated the binding for every
  // secret and whose `Remote ID` was blank for them — a shape that claimed an id nothing writes.
  {
    title: "Created by --commit",
    alias: "secrets",
    note: `.dev.vars secrets marked '${PUSH_MARKER}', created remotely under their own name`,
    types: ["secrets"],
  },
  {
    title: "Provisioned by --commit",
    alias: "provision",
    note: (prefix) => `Bindings created as ${prefix ? `${prefix}_<BINDING>` : "<BINDING>"} with the id written back into wrangler.jsonc`,
    types: ["kv_namespaces", "d1_databases", "r2_buckets", "queues"],
    withType: true,
  },
  {
    title: "Rotated by --commit",
    alias: "rotate",
    note: `.dev.vars keys marked '${GENERATE_MARKER}'; --commit generates remote secret; --rotate rotates secrets`,
    types: ["rotatable_secrets"],
  },
];

/**
 * The resource types one section covers, with the catch-all resolving to whatever no
 * other section claimed.
 *
 * Derived rather than listed twice: `--resources deploy` and the *Pushed by the Next
 * Deploy* section must mean the same set, and the only way to guarantee that is for
 * one of them not to have its own copy.
 */
function typesFor(spec: SectionSpec): ResourceType[] {
  if (spec.types) return spec.types;
  const claimed = new Set(SECTIONS.flatMap((s) => s.types ?? []));
  return RESOURCE_TYPES.filter((t) => !claimed.has(t));
}

/**
 * What each outcome means, as a colour.
 *
 * The reader arrives with one question — *what happens to this name?* — and in a forty-row report
 * the `Action` column is the only one they are really scanning. Five states, not twelve: settled
 * and good, pending until `--commit`, needs a look, broken, and merely informational. Kept here
 * rather than beside `ACTION_LABELS` because a colour is presentation and that table is vocabulary.
 */
function styleAction(action: SyncAction, style: Colorize): string {
  const label = ACTION_LABELS[action];
  switch (action) {
    case "created":
    case "updated":
    case "rotated":
    case "in-sync":
      return style.green(label);
    case "would-create":
    case "would-rotate":
      return style.cyan(label);
    case "drift":
    case "remote-only":
    case "unavailable":
      return style.yellow(label);
    case "error":
      return style.red(label);
    // `local only` and `deploy pushes` are the commonest rows and the ones needing no decision,
    // so they recede rather than compete with the ones that do.
    default:
      return style.dim(label);
  }
}

/** `yes` / `no` for a side that was checked, blank for one that was not. */
const presenceCell = (known: boolean | undefined) => (known === undefined ? "" : known ? "yes" : "no");

/**
 * Build the printable rows for one section.
 *
 * `Remote Name` is dropped when it says nothing the `Binding` column does not — for
 * vars and secrets the two are the same string by construction, and for a prefixed
 * KV namespace they differ and both are worth seeing. That judgement needs to know
 * what a remote name *is*, so it lives here rather than in the table renderer.
 */
function sectionRows(results: SyncResult[], spec: SectionSpec, strip: (detail: string) => string, style: Colorize) {
  // A row with no remote name at all — a rate limiter, say — must not summon the
  // column for the rows that merely repeat their binding in it.
  const named = results.some((r) => r.remoteName !== undefined && r.remoteName !== r.binding);
  const presence = spec.presence !== false;

  return results.map((r) => ({
    ...(spec.withType ? { Type: r.resourceType } : {}),
    Binding: r.binding,
    ...(named ? { "Remote Name": r.remoteName ?? "" } : {}),
    ...(presence ? { Local: presenceCell(r.local), Remote: presenceCell(r.remote) } : {}),
    Action: styleAction(r.action, style),
    "Remote ID": r.remoteId ?? "",
    Detail: strip(r.detail ?? ""),
  }));
}

/**
 * What `--commit` would do, counted from the rows already computed.
 *
 * The footer used to say only that nothing had happened, which is the half of the
 * sentence the reader already knew. Naming the pending work is what turns the report
 * into a decision: a run with nothing to apply reads differently from one with six
 * secrets waiting, and previously the two footers were identical.
 */
/**
 * The rows a reader would act on.
 *
 * A row is **settled** when it is verified equal on both sides, deliberately local,
 * a write this run completed — or when the remote was never queried at all, since
 * "we did not look" is not evidence of drift and must not fail a check.
 */
export function pendingRows(results: SyncResult[]): SyncResult[] {
  const settled = new Set<SyncResult["action"]>(["in-sync", "local-only", "created", "updated", "rotated"]);
  return results.filter((r) => !settled.has(r.action) && r.remote !== undefined);
}

export function summariseCommit(results: SyncResult[]): string {
  const count = (action: SyncResult["action"]) => results.filter((r) => r.action === action).length;
  const parts = [[count("would-create"), "create"] as const, [count("would-rotate"), "rotate"] as const]
    .filter(([n]) => n > 0)
    .map(([n, verb]) => `${verb} ${n}`);

  if (parts.length === 0) return "(status only — nothing was written, and --commit would change nothing here.)";
  return `(status only — nothing was written. --commit would ${parts.join(" and ")}. Re-run with --commit to apply.)`;
}

export function printResults(
  results: SyncResult[],
  target: DeploymentTarget,
  prefix: ResolvedPrefix = "",
  notes: SyncNote[] = [],
  options: TableOptions = {},
): void {
  const style = options.style ?? PLAIN;
  if (results.length === 0 && notes.length === 0) {
    console.log("No bindings found.");
    return;
  }

  // The surface is stated once, in the banner. A `SyncResult.detail` stays
  // self-describing for programmatic callers, so the prefix is removed here — from
  // the exact string the target produced, never from a guessed-at one.
  const surface = `${describeTarget(target)} · `;
  const strip = (detail: string) => (detail.startsWith(surface) ? detail.slice(surface.length) : detail);

  const sections = SECTIONS.map((spec) => {
    const types = new Set(typesFor(spec));
    return {
      title: spec.title,
      note: typeof spec.note === "function" ? spec.note(prefix) : spec.note,
      rows: sectionRows(
        results.filter((r) => types.has(r.resourceType)),
        spec,
        strip,
        style,
      ),
      footers: notes.filter((n) => types.has(n.resourceType)).map((n) => n.message),
    };
  });

  console.log(`${style.bold(`${describeTarget(target)} · ${target.name}`)}\n`);
  // `Action` and `Detail` are prose and may wrap; everything else is an identifier and truncates.
  // The distinction is what the column is for: `create on --commit` cut to `create on -…` has lost
  // the verb, where a binding name cut to `PROJ_CACH…` is still recognisably that binding — and a
  // name broken across two lines is no longer one you can search the config for.
  console.log(renderSections(sections, { ...options, style, wrap: ["Action", "Detail"] }));
}

type LooseFlags = Record<string, string | string[] | boolean | undefined>;

/** What `--json` prints: the whole run, in the vocabulary the types already define. */
interface JsonReport {
  target: SyncOutput["target"];
  prefix: ResolvedPrefix;
  committed: boolean;
  results: SyncResult[];
  notes: SyncNote[];
  pending: number;
  configWrite?: { path: string; edits: number; rewritten: boolean };
}

// `--rotate` is repeatable, so its absence is an empty array — truthy. Every guard that asks
// "was it given?" has to ask about length.
function given(value: LooseFlags[string]): boolean {
  return Array.isArray(value) ? value.length > 0 : value !== undefined && value !== false;
}

async function runSync(flags: LooseFlags, ctx?: CliContext): Promise<void> {
  const commit = Boolean(flags.commit);
  if (!commit && flags.force) {
    throw new CliError("invalid-args", "--force only means something alongside --commit, which is what permits a write.");
  }
  if (commit && flags.check) {
    throw new CliError(
      "invalid-args",
      "--check asks whether anything is pending; --commit applies it. Asking for both is asking whether the change you just made was needed.",
    );
  }
  if (flags.local && !given(flags.rotate)) {
    throw new CliError("invalid-args", "--local only means something alongside --rotate: it is where a rotation writes, not a mode of its own.");
  }
  if (flags.local) return runLocalRotate(flags, commit);

  const auth = resolveAuth(flags);
  const configPath = (flags.config as string) ?? "wrangler.jsonc";
  const json = Boolean(flags.json);
  // `--json` selects PLAIN before anything is rendered. The payload is data rather than
  // presentation and no styler touches it, but stating the choice here means a future styled
  // line cannot be added above the JSON without deciding what it does under `--json`.
  const style = json ? PLAIN : (ctx?.out ?? PLAIN);

  const resources = parseResources(flags.resources as string[] | undefined);
  const rotate = resolveRotation(flags.rotate as string[] | undefined, configPath);
  // Loaded once, with its source text, so write-back splices offsets computed from
  // bytes it actually validated rather than from a re-read after the API round-trip.
  const loaded = loadWranglerConfig(configPath);

  // Before the first request, not after: a confirmation that arrives once half the
  // secrets are already replaced is not a confirmation.
  if (commit) {
    const target = detectTarget(loaded.config, loaded.config.name);
    await confirmRotation(rotate, `${describeTarget(target)} ${target.name}`, flags);
  }

  const output = await syncBindings(
    loaded.config,
    // `dryRun` is the engine's word for the same switch: without --commit, handlers
    // read but never write.
    { auth, dryRun: !commit, prefix: resolvePrefixStrategy(flags), resources, rotate },
    // Rebuilt per invocation so that handlers needing the resolved --config path
    // — secrets, which finds .dev.vars beside it — actually receive it.
    buildHandlers({ configPath }),
  );

  const report: JsonReport = {
    target: output.target,
    prefix: output.prefix,
    committed: commit,
    results: output.results,
    notes: output.notes,
    pending: pendingRows(output.results).length,
  };

  // The width is stdout's, because that is where the grid goes. Absent a context — a direct
  // programmatic call — no width is imposed and the grid is as wide as its content, which is what
  // every caller before this one expected.
  if (!json)
    printResults(output.results, output.target, output.prefix, output.notes, { style, ...(ctx === undefined ? {} : { width: ctx.width }) });

  if (!commit) {
    if (!json) console.log(`\n${summariseCommit(output.results)}`);
  } else if (output.configChanged) {
    const write = writeWranglerConfig(loaded, output.updatedConfig, { force: Boolean(flags.force) });
    if (!write.ok) throw write.error;

    report.configWrite = { path: write.data.path, edits: write.data.edits, rewritten: Boolean(write.data.lost) };

    if (json) {
      // Nothing but the document reaches stdout, or the caller has to parse around it.
    } else if (write.data.lost) {
      // The one destructive outcome `forge sync` has: comments and formatting are gone and cannot
      // be recovered from the file. It is yellow because it is a warning, not a report.
      const { comments, unsupported } = write.data.lost;
      console.log(`\n${style.yellow(`Rewrote ${write.data.path} as plain JSON (--force).`)}`);
      console.log(`  lost: ${comments} comment${comments === 1 ? "" : "s"} and all original formatting`);
      console.log(`  changes that could not be spliced: ${unsupported.join(", ")}`);
    } else if (write.data.written) {
      console.log(
        `\n${style.green(`Updated ${write.data.path}`)} — ${write.data.edits} value${write.data.edits === 1 ? "" : "s"} spliced in; every other byte is unchanged.`,
      );
    }
  }

  if (json) console.log(JSON.stringify(report, null, 2));

  // Signalled without returning early: an `error` row must not suppress the
  // write-back of the rows that did resolve.
  if (output.results.some((r) => r.action === "error")) process.exitCode = 1;
  else if (flags.check && report.pending > 0) process.exitCode = 1;
}

export function createSyncCommand() {
  return createCommand({
    name: "sync",
    description:
      "Compare Cloudflare bindings against the remote and report on them. Read-only unless --commit, which creates the missing resources and writes resolved IDs back into the config",
    flags: syncFlags,
    run: (_args, flags, ctx) => runSync(flags as LooseFlags, ctx),
  });
}
