export { createCfClient } from "./api/client";
export type { CfFailureKind } from "./api/errors";
export { classifyCfError, describeCfFailure } from "./api/errors";
export type { CfApiClientErrorKind } from "./api/types";
export { CfApiClientError } from "./api/types";
export { createSyncCommand, parseResources, pendingRows, printResults, resolveRotation, summariseCommit } from "./commands";
export type { ConfigDiff, JsonPath } from "./config/diff";
export { diffConfig, formatPath } from "./config/diff";
export type { JsoncEdit, JsoncEditError } from "./config/edit";
export { applyJsoncEdits } from "./config/edit";
export type { JsoncNode, JsoncParseError } from "./config/jsonc";
export { countComments, parseJsoncTree } from "./config/jsonc";
export type { LoadedWranglerConfig, WriteOutcome } from "./config/parse";
export { loadWranglerConfig, parseWranglerConfig, stripJsonc, writeWranglerConfig } from "./config/parse";
export { syncBindings } from "./engine";
export type { Verification } from "./handlers/declarative";
export { createDeclarativeHandler, UNVERIFIED_DETAIL } from "./handlers/declarative";
export type { DevVar, DevVarKind } from "./handlers/devvars";
export { devVarsPath, editDevVars, GENERATE_MARKER, PUSH_MARKER, parseDevVars, readDevVars, writeDevVars } from "./handlers/devvars";
export { createLocalVarsHandler } from "./handlers/localvars";
export { dnsName, prefixedName, sanitizeName } from "./handlers/naming";
export { rateLimitsHandler } from "./handlers/ratelimits";
export type { HandlerBuildOptions } from "./handlers/registry";
export { buildHandlers, defaultHandlers, findHandler } from "./handlers/registry";
export type { RotationPlan } from "./handlers/rotate";
export { describeRefusal, planRotation, randomSecret, rotateSecrets } from "./handlers/rotate";
export type { FailureRowOptions, RowIdentity } from "./handlers/rows";
export { failureRows, staleIdDetail } from "./handlers/rows";
export { createRotatableSecretsHandler, createSecretsHandler } from "./handlers/secrets";
export type { HandlerContext, ReconcileResult, ResourceHandler } from "./handlers/types";
export { createVarsHandler } from "./handlers/vars";
export type { TableSection } from "./table";
export { renderSections, renderTable } from "./table";
export type { DeploymentTarget } from "./target";
export { describeTarget, detectTarget } from "./target";
export type { CfAuth, PrefixStrategy, ResourceType, SyncAction, SyncConfig, SyncNote, SyncOutput, SyncResult, WranglerConfig } from "./types";
export { ACTION_LABELS, RESOURCE_TYPES } from "./types";
export { createSyncZoneCommand, planZoneRules, rulesInSync } from "./zone";
