export { renderCatalogue } from "./catalogue/render";
export { createWardenCommands } from "./cli/commands";
export { createCatalogueCommand, createKnowledgeCommands, createServeCommand } from "./cli/knowledge";
export { bindings, DEFAULT_ARCH, declaredVersion, executables, installedVersion, placeNatives } from "./cli/natives";
export type { Subject } from "./cli/show";
export { show, SUBJECTS } from "./cli/show";
export { chunkDocument, frontmatter, glossary, headings, proseOf, ruleClauses } from "./corpus/chunk";
export { fnv1a } from "./corpus/hash";
export { chunkId, headingSlug, parseId, sourceId } from "./corpus/ident";
export { citationTarget, headerOf, relationsOf, resolveDoc } from "./corpus/relate";
export { canonSources, discover, localSources, repoRelative, weightOf } from "./corpus/source";
export type { GoldenCheckConfig } from "./gate/queries";
export { checkGoldenQueries } from "./gate/queries";
export type { GoldenQuery } from "./gate/golden";
export { GOLDEN } from "./gate/golden";
export type { WardenCheckConfig } from "./gate/warden";
export { checkWarden } from "./gate/warden";
export type { BuildReport } from "./index/build";
export { build, load } from "./index/build";
export { gateIndexPath, indexPath, openDatabase, readMeta, stampVersions, versionsMatch, writeMeta } from "./index/db";
export type { Freshness } from "./index/freshness";
export { advisory, freshness } from "./index/freshness";
export type { Knowledge } from "./index/open";
export { openIndex, rebuild } from "./index/open";
export { COLUMN_WEIGHTS, INDEXER_VERSION, SCHEMA, SCHEMA_VERSION, TOKENIZE } from "./index/schema";
export { CANON_ROOT, CLAUDE_ROOT, resolveRepoRoot, walkUpToRepo, WARDEN_ROOT } from "./paths";
export { check, checkAgents, checkTree } from "./sync/check";
export { readKind, resolveKind } from "./sync/kind";
export { seed, seedFiles } from "./sync/seed";
export { copyTree, identical, sync, syncTrees, walk } from "./sync/sync";
export type { Chunk, Corpus, Divergence, Kind, Relation, SeedFile, SourceDoc, SyncOutcome, SyncTree, Tree } from "./types";
export { canonVersion } from "./version";
