import { describe, expect, it } from "bun:test";

import { CliError } from "../cli/errors";
import { appHome, clearLocalState, resolveHome, scratchHome, standbyHome, synthesizeHome } from "./home";
import { fakeDbIo } from "./test-support";
import type { D1Entry, DbConfig } from "./types";

const ENTRY: D1Entry = { binding: "DB", databaseName: "app-db", databaseId: null, previewDatabaseId: null };

function dbConfig(over: Partial<DbConfig> = {}): DbConfig {
  return {
    root: "/app",
    configPath: "/app/wrangler.jsonc",
    config: { name: "app", account_id: "acct-1", compatibility_date: "2026-01-01" },
    env: null,
    entry: ENTRY,
    target: { place: "local", database: null },
    ...over,
  };
}

const STANDBY_OPTIONS = { label: "standby", database: "app-db-standby", dir: "/app/.forge/standby/app-db-standby" };

describe("appHome()", () => {
  it("runs in the config's directory and persists beside it", () => {
    expect(appHome(dbConfig())).toEqual({
      label: "local",
      database: "app-db",
      dir: "/app",
      configPath: "/app/wrangler.jsonc",
      persistTo: "/app/.wrangler/state",
      place: "local",
      env: null,
      synthesized: false,
    });
  });

  it("has no state directory for a deployed database", () => {
    expect(appHome(dbConfig({ target: { place: "remote", database: null } })).persistTo).toBeNull();
    expect(appHome(dbConfig({ target: { place: "preview", database: null } })).persistTo).toBeNull();
  });

  it("carries the wrangler environment", () => {
    expect(appHome(dbConfig({ env: "staging" })).env).toBe("staging");
  });

  it("is never a generated config", () => {
    expect(appHome(dbConfig()).synthesized).toBe(false);
  });
});

describe("synthesizeHome()", () => {
  it("writes a config naming the second database, with the app's account and compatibility date", () => {
    const io = fakeDbIo();
    const home = synthesizeHome(dbConfig(), io, STANDBY_OPTIONS);
    expect(io.readText("/app/.forge/standby/app-db-standby/wrangler.jsonc")).toBe(`{
  "$comment": "Generated by forge db. Not checked in, not read by the Worker, safe to delete.",
  "send_metrics": false,
  "name": "app",
  "account_id": "acct-1",
  "compatibility_date": "2026-01-01",
  "d1_databases": [
    {
      "binding": "DB",
      "database_name": "app-db-standby",
      "database_id": "app-db-standby-local"
    }
  ]
}
`);
    expect(home).toEqual({
      label: "standby",
      database: "app-db-standby",
      dir: "/app/.forge/standby/app-db-standby",
      configPath: "/app/.forge/standby/app-db-standby/wrangler.jsonc",
      persistTo: "/app/.forge/standby/app-db-standby/.wrangler/state",
      place: "local",
      env: null,
      synthesized: true,
    });
  });

  it("omits an account id and a compatibility date the app's config does not carry", () => {
    const io = fakeDbIo();
    synthesizeHome(dbConfig({ config: { name: "app" } }), io, STANDBY_OPTIONS);
    expect(io.readText("/app/.forge/standby/app-db-standby/wrangler.jsonc")).toBe(`{
  "$comment": "Generated by forge db. Not checked in, not read by the Worker, safe to delete.",
  "send_metrics": false,
  "name": "app",
  "d1_databases": [
    {
      "binding": "DB",
      "database_name": "app-db-standby",
      "database_id": "app-db-standby-local"
    }
  ]
}
`);
  });

  it("keeps the app's own database id, and carries a preview id when there is one", () => {
    const io = fakeDbIo();
    const entry = { ...ENTRY, databaseId: "0f8c2a5e-1b2c-4d3e-8f9a-0b1c2d3e4f5a", previewDatabaseId: "1a2b3c4d-5e6f-4a7b-8c9d-0e1f2a3b4c5d" };
    synthesizeHome(dbConfig({ entry }), io, STANDBY_OPTIONS);
    expect(JSON.parse(io.readText("/app/.forge/standby/app-db-standby/wrangler.jsonc")).d1_databases).toEqual([
      {
        binding: "DB",
        database_name: "app-db-standby",
        database_id: "0f8c2a5e-1b2c-4d3e-8f9a-0b1c2d3e4f5a",
        preview_database_id: "1a2b3c4d-5e6f-4a7b-8c9d-0e1f2a3b4c5d",
      },
    ]);
  });

  it("has no state directory when the target is deployed", () => {
    const io = fakeDbIo();
    expect(synthesizeHome(dbConfig({ target: { place: "remote", database: null } }), io, STANDBY_OPTIONS).persistTo).toBeNull();
  });

  it("takes a state directory the caller names, so a cut apply writes into the real database", () => {
    const io = fakeDbIo();
    const home = synthesizeHome(dbConfig(), io, { ...STANDBY_OPTIONS, persistTo: "/app/.wrangler/state" });
    expect(home.persistTo).toBe("/app/.wrangler/state");
  });

  it("creates the directory it writes into", () => {
    const io = fakeDbIo();
    synthesizeHome(dbConfig(), io, STANDBY_OPTIONS);
    expect(io.exists("/app/.forge/standby/app-db-standby")).toBe(true);
  });

  it("drops the environment, because the generated config has no env blocks to select from", () => {
    const io = fakeDbIo();
    expect(synthesizeHome(dbConfig({ env: "staging" }), io, STANDBY_OPTIONS).env).toBeNull();
  });
});

describe("standbyHome()", () => {
  it("names the database after the app's and puts it under .forge/standby", () => {
    const io = fakeDbIo();
    const home = standbyHome(dbConfig({ target: { place: "standby", database: null } }), io);
    expect([home.label, home.database, home.dir, home.synthesized]).toEqual([
      "standby",
      "app-db-standby",
      "/app/.forge/standby/app-db-standby",
      true,
    ]);
  });

  it("honours the database the target names", () => {
    const io = fakeDbIo();
    const home = standbyHome(dbConfig({ target: { place: "standby", database: "rehearsal" } }), io);
    expect([home.database, home.dir]).toEqual(["rehearsal", "/app/.forge/standby/rehearsal"]);
  });
});

describe("scratchHome()", () => {
  it("labels itself with the run's name and lives under .forge/scratch", () => {
    const io = fakeDbIo();
    const home = scratchHome(dbConfig(), io, "restore-check", "app-db-verify");
    expect([home.label, home.database, home.dir, home.configPath]).toEqual([
      "scratch:restore-check",
      "app-db-verify",
      "/app/.forge/scratch/restore-check",
      "/app/.forge/scratch/restore-check/wrangler.jsonc",
    ]);
  });
});

describe("clearLocalState()", () => {
  const STATE = "v3/d1/miniflare-D1DatabaseObject/db.sqlite";

  it("removes a generated home's state and nothing else", () => {
    const io = fakeDbIo({ [`/app/.forge/standby/app-db-standby/.wrangler/state/${STATE}`]: "", [`/app/.wrangler/state/${STATE}`]: "" });
    clearLocalState(io, synthesizeHome(dbConfig(), io, STANDBY_OPTIONS));
    expect(io.exists(`/app/.forge/standby/app-db-standby/.wrangler/state/${STATE}`)).toBe(false);
    expect(io.exists(`/app/.wrangler/state/${STATE}`)).toBe(true);
  });

  it("accepts a real standbyHome, which is the precondition `runStandbyReset` leans on", () => {
    const io = fakeDbIo({ [`/app/.forge/standby/app-db-standby/.wrangler/state/${STATE}`]: "" });
    clearLocalState(io, standbyHome(dbConfig({ target: { place: "standby", database: null } }), io));
    expect(io.exists(`/app/.forge/standby/app-db-standby/.wrangler/state/${STATE}`)).toBe(false);
  });

  it("refuses the app's own home, whose state is not `.forge/`'s to throw away", () => {
    const io = fakeDbIo({ [`/app/.wrangler/state/${STATE}`]: "" });
    expect(() => clearLocalState(io, appHome(dbConfig()))).toThrow(
      "local is the app's own database — only a generated home's state is removed here",
    );
    expect(() => clearLocalState(io, appHome(dbConfig()))).toThrow(CliError);
    expect(io.exists(`/app/.wrangler/state/${STATE}`)).toBe(true);
  });

  it("refuses a deployed home before it looks at the flag", () => {
    const io = fakeDbIo();
    expect(() => clearLocalState(io, synthesizeHome(dbConfig({ target: { place: "remote", database: null } }), io, STANDBY_OPTIONS))).toThrow(
      "standby is a deployed database — nothing here removes its state",
    );
  });
});

describe("resolveHome()", () => {
  it("generates a home for standby and uses the checked-in config for every other place", () => {
    const io = fakeDbIo();
    const places = (["local", "standby", "remote", "preview"] as const).map((place) => {
      const home = resolveHome(dbConfig({ target: { place, database: null } }), io);
      return [home.label, home.synthesized];
    });
    expect(places).toEqual([
      ["local", false],
      ["standby", true],
      ["remote", false],
      ["preview", false],
    ]);
  });
});
