import { dirname, join } from "node:path";

import { CliError } from "../cli/errors";
import type { DbConfig, DbIo, Home, SynthesizeOptions } from "./types";

/** Where wrangler keeps a local home's state: the `--persist-to` argument's own `v3` child, which is what anything reading that state opens. @internal */
export function persistRoot(home: Home): string {
  return join(home.persistTo ?? home.dir, "v3");
}

/** The app's own database: the checked-in config, and wrangler's default state directory beside it. @internal */
export function appHome(config: DbConfig): Home {
  const dir = dirname(config.configPath);
  const remote = config.target.place === "remote" || config.target.place === "preview";
  return {
    label: config.target.place,
    database: config.entry.databaseName,
    binding: config.entry.binding,
    dir,
    configPath: config.configPath,
    persistTo: remote ? null : join(dir, ".wrangler", "state"),
    place: config.target.place,
    env: config.env,
    synthesized: false,
  };
}

/** Writes a config derived from the app's, so a second database or a cut migration list is reachable with no second checked-in file. @internal */
export function synthesizeHome(config: DbConfig, io: DbIo, options: SynthesizeOptions): Home {
  io.mkdir(options.dir);
  const configPath = join(options.dir, "wrangler.jsonc");
  const source = config.config;
  const remote = config.target.place === "remote" || config.target.place === "preview";
  const entry = {
    binding: config.entry.binding,
    database_name: options.database,
    database_id: remote ? config.entry.databaseId : (config.entry.databaseId ?? `${options.database}-local`),
    ...(config.entry.previewDatabaseId === null ? {} : { preview_database_id: config.entry.previewDatabaseId }),
  };
  const generated = {
    send_metrics: false,
    name: source.name,
    ...(typeof source.account_id === "string" ? { account_id: source.account_id } : {}),
    ...(typeof source.compatibility_date === "string" ? { compatibility_date: source.compatibility_date } : {}),
    d1_databases: [entry],
  };
  // The note is a JSONC comment rather than a field: wrangler holds its config to a schema and warns
  // on a key it does not know, and that warning is on the reading process's own stderr.
  const note = "// Generated by forge db. Not checked in, not read by the Worker, safe to delete.";
  io.writeText(configPath, `${note}\n${JSON.stringify(generated, null, 2)}\n`);
  return {
    label: options.label,
    database: options.database,
    binding: config.entry.binding,
    dir: options.dir,
    configPath,
    persistTo: remote ? null : (options.persistTo ?? join(options.dir, ".wrangler", "state")),
    place: config.target.place,
    env: null,
    synthesized: true,
  };
}

/** The second local database, under `.forge/standby/`, which nothing it does can reach the live state from. @internal */
export function standbyHome(config: DbConfig, io: DbIo): Home {
  const database = config.target.database ?? `${config.entry.databaseName}-standby`;
  return synthesizeHome(config, io, { label: "standby", database, dir: join(config.root, ".forge", "standby", database) });
}

/** A throwaway home under `.forge/scratch/`, used to prove a restore without touching anything live. @internal */
export function scratchHome(config: DbConfig, io: DbIo, name: string, database: string): Home {
  return synthesizeHome(config, io, { label: `scratch:${name}`, database, dir: join(config.root, ".forge", "scratch", name) });
}

/** The home a target resolves to: the app's for `local`, `remote` and `preview`, a generated one for `standby`. @internal */
export function resolveHome(config: DbConfig, io: DbIo): Home {
  return config.target.place === "standby" ? standbyHome(config, io) : appHome(config);
}

/** Removes a generated local home's miniflare state, so the next statement starts from an empty database; the app's own home and a deployed one are refused. @internal */
export async function clearLocalState(io: DbIo, home: Home): Promise<void> {
  if (home.persistTo === null) throw new CliError("invalid-args", `${home.label} is a deployed database — nothing here removes its state`);
  if (!home.synthesized)
    throw new CliError("invalid-args", `${home.label} is the app's own database — only a generated home's state is removed here`);
  await io.closeD1(home);
  io.remove(join(persistRoot(home), "d1", "miniflare-D1DatabaseObject"));
}
