import { dirname, join } from "node:path";

import { CliError } from "../cli/errors";
import type { DbConfig, DbIo, Home, Migration, SynthesizeOptions } from "./types";

/** The app's own database: the checked-in config, and wrangler's default state directory beside it. @internal */
export function appHome(config: DbConfig): Home {
  const dir = dirname(config.configPath);
  const remote = config.target.place === "remote" || config.target.place === "preview";
  return {
    label: config.target.place,
    database: config.entry.databaseName,
    dir,
    configPath: config.configPath,
    persistTo: remote ? null : join(dir, ".wrangler", "state"),
    place: config.target.place,
    env: config.env,
    synthesized: false,
  };
}

/** Writes a config derived from the app's, so a second database or a cut migration list is reachable with no second checked-in file. @internal */
export function synthesizeHome(config: DbConfig, io: DbIo, options: SynthesizeOptions): Home {
  io.mkdir(options.dir);
  const configPath = join(options.dir, "wrangler.jsonc");
  const source = config.config;
  const remote = config.target.place === "remote" || config.target.place === "preview";
  const entry = {
    binding: config.entry.binding,
    database_name: options.database,
    database_id: remote ? config.entry.databaseId : (config.entry.databaseId ?? `${options.database}-local`),
    ...(config.entry.previewDatabaseId === null ? {} : { preview_database_id: config.entry.previewDatabaseId }),
    migrations_dir: options.migrationsDir,
    migrations_table: config.entry.migrationsTable,
  };
  const generated = {
    $comment: "Generated by forge db. Not checked in, not read by the Worker, safe to delete.",
    send_metrics: false,
    name: source.name,
    ...(typeof source.account_id === "string" ? { account_id: source.account_id } : {}),
    ...(typeof source.compatibility_date === "string" ? { compatibility_date: source.compatibility_date } : {}),
    d1_databases: [entry],
  };
  io.writeText(configPath, `${JSON.stringify(generated, null, 2)}\n`);
  return {
    label: options.label,
    database: options.database,
    dir: options.dir,
    configPath,
    persistTo: remote ? null : (options.persistTo ?? join(options.dir, ".wrangler", "state")),
    place: config.target.place,
    env: null,
    synthesized: true,
  };
}

/** Writes the migration set an apply runs under `.forge/scratch/`, so a `--to` cut reaches the real database. @internal */
export function migrationsHome(config: DbConfig, io: DbIo, migrations: readonly Migration[], label: string, from: Home): Home {
  const dir = join(config.root, ".forge", "scratch", label);
  const migrationsDir = join(dir, "migrations");
  io.remove(migrationsDir);
  io.mkdir(migrationsDir);
  for (const migration of migrations) io.writeText(join(migrationsDir, `${migration.name}.sql`), migration.sql);
  return synthesizeHome(config, io, {
    label,
    database: from.database,
    dir,
    migrationsDir,
    ...(from.persistTo === null ? {} : { persistTo: from.persistTo }),
  });
}

/** The second local database, under `.forge/standby/`, which nothing it does can reach the live state from. @internal */
export function standbyHome(config: DbConfig, io: DbIo, migrationsDir: string): Home {
  const database = config.target.database ?? `${config.entry.databaseName}-standby`;
  return synthesizeHome(config, io, { label: "standby", database, dir: join(config.root, ".forge", "standby", database), migrationsDir });
}

/** A throwaway home under `.forge/scratch/`, used to prove a restore without touching anything live. @internal */
export function scratchHome(config: DbConfig, io: DbIo, name: string, database: string, migrationsDir: string): Home {
  return synthesizeHome(config, io, { label: `scratch:${name}`, database, dir: join(config.root, ".forge", "scratch", name), migrationsDir });
}

/** The home a target resolves to: the app's for `local`, `remote` and `preview`, a generated one for `standby`. @internal */
export function resolveHome(config: DbConfig, io: DbIo): Home {
  return config.target.place === "standby" ? standbyHome(config, io, config.entry.migrationsDir) : appHome(config);
}

/** Removes a generated local home's miniflare state, so the next statement starts from an empty database; the app's own home and a deployed one are refused. @internal */
export function clearLocalState(io: DbIo, home: Home): void {
  if (home.persistTo === null) throw new CliError("invalid-args", `${home.label} is a deployed database — nothing here removes its state`);
  if (!home.synthesized)
    throw new CliError("invalid-args", `${home.label} is the app's own database — only a generated home's state is removed here`);
  io.remove(join(home.persistTo, "v3", "d1", "miniflare-D1DatabaseObject"));
}
