// AUTO-GENERATED by @y-core/forge assets build — do not edit.
import { createManifest } from "@y-core/forge/assets/manifest";

const DATA: Record<string, string> = {

};

export const assets = createManifest(DATA, "/assets");
