import { afterEach, beforeEach, describe, expect, it } from "bun:test";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";

import type { GateMode } from "../steps";
import { checkAssetManifest } from "./asset-manifest";

let root: string;

const BUILD_HEADER = "// AUTO-GENERATED by @y-core/forge assets build — do not edit.";

const TYPES_HEADER = [
  "// AUTO-GENERATED by `forge assets gen types` from assets.config.ts — do not edit.",
  "// TYPES ONLY: every path here is the unhashed logical name and every viewBox is empty.",
  "// Run `forge assets build all` before serving — this artifact is for typecheck and tests.",
].join("\n");

function writeConfig(): void {
  writeFileSync(join(root, "assets.config.ts"), `export default { paths: { publicDir: "public/assets" } };\n`);
}

function writeModule(data: Record<string, string>, header: string = BUILD_HEADER): void {
  const entries = Object.entries(data)
    .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`)
    .join("\n");
  writeRaw(`${header}
import { createManifest } from "@y-core/forge/assets";

const DATA: Record<string, string> = {
${entries}
};

export const assets = createManifest(DATA, "/assets");
`);
}

function writeRaw(content: string): void {
  const path = join(root, ".forge", "assets.ts");
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
}

function writeAsset(relative: string): void {
  const path = join(root, "public", "assets", relative);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, "built");
}

const run = (mode: GateMode = "fast") => checkAssetManifest({ root, assetConfig: "assets.config.ts" }, mode);

beforeEach(() => {
  root = mkdtempSync(join(tmpdir(), "forge-asset-manifest-"));
  mkdirSync(join(root, "public", "assets"), { recursive: true });
  writeConfig();
});

afterEach(() => {
  rmSync(root, { recursive: true, force: true });
});

describe("checkAssetManifest", () => {
  it("passes when every mapped value exists under publicDir", async () => {
    writeModule({ "css/app.css": "css/app-AAAA1111.css", "js/main.js": "js/main-DIUBTM66.js" });
    writeAsset("css/app-AAAA1111.css");
    writeAsset("js/main-DIUBTM66.js");

    const result = await run();

    expect(result.ok).toBe(true);
    expect(result.findings).toEqual([]);
    expect(result.summary).toBe("asset manifest: 2 entries verified under `public/assets`");
  });

  it("fails naming the key, the value and the served directory when a file is missing", async () => {
    writeModule({ "css/app.css": "css/app-AAAA1111.css", "js/main.js": "js/main-DIUBTM66.js" });
    writeAsset("css/app-AAAA1111.css");

    const result = await run();

    expect(result.ok).toBe(false);
    expect(result.findings.map((f) => f.message)).toEqual(["`js/main.js` maps to `js/main-DIUBTM66.js`, which is not under `public/assets`"]);
    expect(result.findings.map((f) => f.detail)).toEqual([["run `forge assets build --minify` — the manifest is ahead of the built tree"]]);
  });

  it("reports every missing value, sorted by key", async () => {
    writeModule({ "js/main.js": "js/main-DIUBTM66.js", "css/app.css": "css/app-AAAA1111.css" });

    const result = await run();

    expect(result.ok).toBe(false);
    expect(result.findings.map((f) => f.message)).toEqual([
      "`css/app.css` maps to `css/app-AAAA1111.css`, which is not under `public/assets`",
      "`js/main.js` maps to `js/main-DIUBTM66.js`, which is not under `public/assets`",
    ]);
  });

  it("reports a value escaping publicDir as the plain miss it is", async () => {
    writeModule({ "js/main.js": "../../elsewhere/main.js" });

    const result = await run();

    expect(result.ok).toBe(false);
    expect(result.findings.map((f) => f.message)).toEqual(["`js/main.js` maps to `../../elsewhere/main.js`, which is not under `public/assets`"]);
  });

  it("passes a types-only artifact in a fast run, whose paths no build has produced", async () => {
    writeModule({ "js/main.js": "js/main.js" }, TYPES_HEADER);

    const result = await run("fast");

    expect(result.ok).toBe(true);
    expect(result.findings).toEqual([]);
    expect(result.summary).toBe("asset manifest: types-only artifact, nothing to verify");
  });

  it("fails a types-only artifact in a standard or full run, where a green would ship an unbuilt tree", async () => {
    writeModule({ "js/main.js": "js/main.js" }, TYPES_HEADER);

    expect((await run("standard")).ok).toBe(false);

    const result = await run("full");

    expect(result.ok).toBe(false);
    expect(result.findings.map((f) => f.message)).toEqual([
      "`.forge/assets.ts` is the types-only artifact, whose paths are logical names no build has produced",
    ]);
    expect(result.findings.map((f) => f.detail)).toEqual([
      ["run `forge assets build --minify` — only a fast run accepts an artifact that was never built"],
    ]);
    expect(result.summary).toBe("asset manifest: types-only artifact");
  });

  it("passes an empty manifest in every mode, since an icons-only config emits no entries", async () => {
    writeModule({});

    for (const mode of ["fast", "standard", "full"] as const) {
      const result = await run(mode);
      expect(result.ok).toBe(true);
      expect(result.findings).toEqual([]);
      expect(result.summary).toBe("asset manifest: empty, nothing to verify");
    }
  });

  it("fails when the emitted module is absent rather than reporting a clean tree", async () => {
    const result = await run();

    expect(result.ok).toBe(false);
    expect(result.findings.map((f) => f.message)).toEqual(["`.forge/assets.ts` not found"]);
    expect(result.summary).toBe("asset manifest: no emitted module");
  });

  it("fails on a file with no DATA block, distinctly from an empty manifest", async () => {
    writeRaw("export const assets = {};\n");

    const result = await run();

    expect(result.ok).toBe(false);
    expect(result.findings.map((f) => f.message)).toEqual(["`.forge/assets.ts` declares no `DATA` block, so it is not an emitted assets module"]);
    expect(result.summary).toBe("asset manifest: not an emitted module");
  });
});
