import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

import { checkResult, fail } from "../finding";
import type { CheckResult } from "../types";
import type { IccProfileCheckConfig } from "./types";

// Chunked for the same reason `font-emit` chunks: spreading a profile into one call is what
// overflows the argument stack, and `btoa` is the exact inverse of the decoder the module ships.
function base64(bytes: Uint8Array): string {
  let binary = "";
  for (let at = 0; at < bytes.length; at += 0x8000) binary += String.fromCharCode(...bytes.subarray(at, at + 0x8000));
  return btoa(binary);
}

/** The generated module embedding `bytes` as the profile a PDF/A render declares. @public */
export function renderIccModule(source: string, bytes: Uint8Array): string {
  return `// sRGB2014.icc — Copyright International Color Consortium, 2015. Published by the ICC at
// https://www.color.org/srgbprofiles.xalter and made available to be copied, distributed, embedded,
// made, used and sold without restriction; an altered profile may not be passed off as the original.
// AUTO-GENERATED by \`bun run gen:icc\` from ${source} — do not edit.
// Decoded on first use, so a consumer that never asks for PDF/A carries the string and nothing else.

let decoded: Uint8Array<ArrayBuffer> | undefined;

const ENCODED =
  ${JSON.stringify(base64(bytes))};

/** The sRGB profile a PDF/A render embeds as its \`/DestOutputProfile\`. @internal */
export function srgbProfile(): Uint8Array<ArrayBuffer> {
  if (decoded === undefined) {
    const binary = atob(ENCODED);
    decoded = new Uint8Array(binary.length);
    for (let at = 0; at < binary.length; at += 1) decoded[at] = binary.charCodeAt(at);
  }
  return decoded;
}
`;
}

// Compared as bytes rather than as text: the generated module is formatted after it is written, so
// a text comparison would report drift on every run without a single byte having changed.
/** Re-decodes the committed module and reports any drift from the `.icc` beside it. @public */
export function checkIccProfile(config: IccProfileCheckConfig): CheckResult {
  const profile = new Uint8Array(readFileSync(resolve(config.root, config.profile)));
  let module: string;
  try {
    module = readFileSync(resolve(config.root, config.module), "utf-8");
  } catch {
    return checkResult([fail("the generated ICC module is missing", { file: config.module, detail: ["run `bun run gen:icc`"] })], "");
  }
  const encoded = /"([A-Za-z0-9+/=]+)"/.exec(module)?.[1] ?? "";
  const drift = encoded !== base64(profile);
  if (drift) {
    return checkResult(
      [
        fail("the committed ICC module no longer carries the profile beside it", {
          file: config.module,
          detail: [
            `\`${config.profile}\` encodes to something else — a replaced profile, or a hand edit`,
            "run `bun run gen:icc` and review the diff",
          ],
        }),
      ],
      "",
    );
  }
  // The profile itself is held too, because a valid encoding of an invalid profile is a file that
  // declares an output intent no checker accepts: PDF/A admits only a `prtr` or `mntr` device class.
  const view = new DataView(profile.buffer, profile.byteOffset, profile.byteLength);
  const declared = view.getUint32(0);
  const device = String.fromCharCode(...profile.subarray(12, 16));
  const signature = String.fromCharCode(...profile.subarray(36, 40));
  const findings = [
    declared === profile.length ? undefined : `its header declares ${declared} bytes and the file is ${profile.length}`,
    signature === "acsp" ? undefined : `its profile signature is ${signature} rather than acsp`,
    device === "mntr" || device === "prtr" ? undefined : `its device class is ${device}, and PDF/A admits only mntr or prtr`,
  ].filter((detail): detail is string => detail !== undefined);
  if (findings.length > 0)
    return checkResult([fail("the ICC profile is not one PDF/A can name as an output intent", { file: config.profile, detail: findings })], "");
  return checkResult([], `${config.module} carries ${config.profile}, a ${device} profile of ${profile.length} bytes`);
}

if (import.meta.main) {
  const root = resolve(import.meta.dir, "../../../..");
  const profile = "src/output/pdf/sRGB2014.icc";
  writeFileSync(resolve(root, "src/output/pdf/icc.ts"), renderIccModule(profile, new Uint8Array(readFileSync(resolve(root, profile)))));
}
