/** class-groups.ts — GENERATED — do not edit; run `bun run gen:class-groups`. */

const STATIC_GROUPS: ReadonlyMap<string, string> = new Map<string, string>([
  ["@container", "container-type"],
  ["absolute", "position"],
  ["accent-auto", "accent-color"],
  ["align-baseline", "vertical-align"],
  ["align-bottom", "vertical-align"],
  ["align-middle", "vertical-align"],
  ["align-sub", "vertical-align"],
  ["align-super", "vertical-align"],
  ["align-text-bottom", "vertical-align"],
  ["align-text-top", "vertical-align"],
  ["align-top", "vertical-align"],
  ["antialiased", "-moz-osx-font-smoothing,-webkit-font-smoothing"],
  ["appearance-auto", "appearance"],
  ["appearance-none", "appearance"],
  ["backdrop-blur", "--tw-backdrop-blur"],
  ["backdrop-filter", "-webkit-backdrop-filter,backdrop-filter"],
  ["backdrop-grayscale", "--tw-backdrop-grayscale"],
  ["backdrop-invert", "--tw-backdrop-invert"],
  ["backdrop-sepia", "--tw-backdrop-sepia"],
  ["backface-hidden", "backface-visibility"],
  ["backface-visible", "backface-visibility"],
  ["basis-auto", "flex-basis"],
  ["basis-full", "flex-basis"],
  ["basis-px", "flex-basis"],
  ["bg-auto", "background-size"],
  ["bg-blend-color", "background-blend-mode"],
  ["bg-blend-color-burn", "background-blend-mode"],
  ["bg-blend-color-dodge", "background-blend-mode"],
  ["bg-blend-darken", "background-blend-mode"],
  ["bg-blend-difference", "background-blend-mode"],
  ["bg-blend-exclusion", "background-blend-mode"],
  ["bg-blend-hard-light", "background-blend-mode"],
  ["bg-blend-hue", "background-blend-mode"],
  ["bg-blend-lighten", "background-blend-mode"],
  ["bg-blend-luminosity", "background-blend-mode"],
  ["bg-blend-multiply", "background-blend-mode"],
  ["bg-blend-normal", "background-blend-mode"],
  ["bg-blend-overlay", "background-blend-mode"],
  ["bg-blend-saturation", "background-blend-mode"],
  ["bg-blend-screen", "background-blend-mode"],
  ["bg-blend-soft-light", "background-blend-mode"],
  ["bg-bottom", "background-position"],
  ["bg-bottom-left", "background-position"],
  ["bg-bottom-right", "background-position"],
  ["bg-center", "background-position"],
  ["bg-clip-border", "background-clip"],
  ["bg-clip-content", "background-clip"],
  ["bg-clip-padding", "background-clip"],
  ["bg-clip-text", "background-clip"],
  ["bg-conic", "--tw-gradient-position"],
  ["bg-contain", "background-size"],
  ["bg-cover", "background-size"],
  ["bg-fixed", "background-attachment"],
  ["bg-gradient-to-b", "--tw-gradient-position"],
  ["bg-gradient-to-bl", "--tw-gradient-position"],
  ["bg-gradient-to-br", "--tw-gradient-position"],
  ["bg-gradient-to-l", "--tw-gradient-position"],
  ["bg-gradient-to-r", "--tw-gradient-position"],
  ["bg-gradient-to-t", "--tw-gradient-position"],
  ["bg-gradient-to-tl", "--tw-gradient-position"],
  ["bg-gradient-to-tr", "--tw-gradient-position"],
  ["bg-left", "background-position"],
  ["bg-left-bottom", "background-position"],
  ["bg-left-top", "background-position"],
  ["bg-local", "background-attachment"],
  ["bg-no-repeat", "background-repeat"],
  ["bg-none", "background-image"],
  ["bg-origin-border", "background-origin"],
  ["bg-origin-content", "background-origin"],
  ["bg-origin-padding", "background-origin"],
  ["bg-radial", "--tw-gradient-position"],
  ["bg-repeat", "background-repeat"],
  ["bg-repeat-round", "background-repeat"],
  ["bg-repeat-space", "background-repeat"],
  ["bg-repeat-x", "background-repeat"],
  ["bg-repeat-y", "background-repeat"],
  ["bg-right", "background-position"],
  ["bg-right-bottom", "background-position"],
  ["bg-right-top", "background-position"],
  ["bg-scroll", "background-attachment"],
  ["bg-top", "background-position"],
  ["bg-top-left", "background-position"],
  ["bg-top-right", "background-position"],
  ["block", "display"],
  ["block-auto", "block-size"],
  ["block-dvh", "block-size"],
  ["block-fit", "block-size"],
  ["block-full", "block-size"],
  ["block-lh", "block-size"],
  ["block-lvh", "block-size"],
  ["block-max", "block-size"],
  ["block-min", "block-size"],
  ["block-px", "block-size"],
  ["block-screen", "block-size"],
  ["block-svh", "block-size"],
  ["blur", "--tw-blur"],
  ["border", "border-style,border-width"],
  ["border-b", "border-bottom-style,border-bottom-width"],
  ["border-be", "border-block-end-style,border-block-end-width"],
  ["border-bs", "border-block-start-style,border-block-start-width"],
  ["border-collapse", "border-collapse"],
  ["border-dashed", "--tw-border-style"],
  ["border-dotted", "--tw-border-style"],
  ["border-double", "--tw-border-style"],
  ["border-e", "border-inline-end-style,border-inline-end-width"],
  ["border-field", "border-width"],
  ["border-hidden", "--tw-border-style"],
  ["border-l", "border-left-style,border-left-width"],
  ["border-none", "--tw-border-style"],
  ["border-r", "border-right-style,border-right-width"],
  ["border-s", "border-inline-start-style,border-inline-start-width"],
  ["border-separate", "border-collapse"],
  ["border-solid", "--tw-border-style"],
  ["border-spacing-px", "--tw-border-spacing-x,--tw-border-spacing-y"],
  ["border-spacing-x-px", "--tw-border-spacing-x"],
  ["border-spacing-y-px", "--tw-border-spacing-y"],
  ["border-t", "border-top-style,border-top-width"],
  ["border-x", "border-inline-style,border-inline-width"],
  ["border-y", "border-block-style,border-block-width"],
  ["bottom-auto", "bottom"],
  ["bottom-full", "bottom"],
  ["bottom-px", "bottom"],
  ["box-border", "box-sizing"],
  ["box-content", "box-sizing"],
  ["box-decoration-clone", "-webkit-box-decoration-break,box-decoration-break"],
  ["box-decoration-slice", "-webkit-box-decoration-break,box-decoration-break"],
  ["break-after-all", "break-after"],
  ["break-after-auto", "break-after"],
  ["break-after-avoid", "break-after"],
  ["break-after-avoid-page", "break-after"],
  ["break-after-column", "break-after"],
  ["break-after-left", "break-after"],
  ["break-after-page", "break-after"],
  ["break-after-right", "break-after"],
  ["break-all", "word-break"],
  ["break-before-all", "break-before"],
  ["break-before-auto", "break-before"],
  ["break-before-avoid", "break-before"],
  ["break-before-avoid-page", "break-before"],
  ["break-before-column", "break-before"],
  ["break-before-left", "break-before"],
  ["break-before-page", "break-before"],
  ["break-before-right", "break-before"],
  ["break-inside-auto", "break-inside"],
  ["break-inside-avoid", "break-inside"],
  ["break-inside-avoid-column", "break-inside"],
  ["break-inside-avoid-page", "break-inside"],
  ["break-keep", "word-break"],
  ["break-normal", "overflow-wrap,word-break"],
  ["break-words", "overflow-wrap"],
  ["capitalize", "text-transform"],
  ["caption-bottom", "caption-side"],
  ["caption-top", "caption-side"],
  ["clear-both", "clear"],
  ["clear-end", "clear"],
  ["clear-left", "clear"],
  ["clear-none", "clear"],
  ["clear-right", "clear"],
  ["clear-start", "clear"],
  ["collapse", "visibility"],
  ["contain-content", "contain"],
  ["contain-inline-size", "--tw-contain-size"],
  ["contain-layout", "--tw-contain-layout"],
  ["contain-none", "contain"],
  ["contain-paint", "--tw-contain-paint"],
  ["contain-size", "--tw-contain-size"],
  ["contain-strict", "contain"],
  ["contain-style", "--tw-contain-style"],
  ["container", "max-width,width"],
  ["content-around", "align-content"],
  ["content-baseline", "align-content"],
  ["content-between", "align-content"],
  ["content-center", "align-content"],
  ["content-center-safe", "align-content"],
  ["content-end", "align-content"],
  ["content-end-safe", "align-content"],
  ["content-evenly", "align-content"],
  ["content-none", "--tw-content"],
  ["content-normal", "align-content"],
  ["content-start", "align-content"],
  ["content-stretch", "align-content"],
  ["contents", "display"],
  ["cursor-alias", "cursor"],
  ["cursor-all-scroll", "cursor"],
  ["cursor-auto", "cursor"],
  ["cursor-cell", "cursor"],
  ["cursor-col-resize", "cursor"],
  ["cursor-context-menu", "cursor"],
  ["cursor-copy", "cursor"],
  ["cursor-crosshair", "cursor"],
  ["cursor-default", "cursor"],
  ["cursor-e-resize", "cursor"],
  ["cursor-ew-resize", "cursor"],
  ["cursor-grab", "cursor"],
  ["cursor-grabbing", "cursor"],
  ["cursor-help", "cursor"],
  ["cursor-move", "cursor"],
  ["cursor-n-resize", "cursor"],
  ["cursor-ne-resize", "cursor"],
  ["cursor-nesw-resize", "cursor"],
  ["cursor-no-drop", "cursor"],
  ["cursor-none", "cursor"],
  ["cursor-not-allowed", "cursor"],
  ["cursor-ns-resize", "cursor"],
  ["cursor-nw-resize", "cursor"],
  ["cursor-nwse-resize", "cursor"],
  ["cursor-pointer", "cursor"],
  ["cursor-progress", "cursor"],
  ["cursor-row-resize", "cursor"],
  ["cursor-s-resize", "cursor"],
  ["cursor-se-resize", "cursor"],
  ["cursor-sw-resize", "cursor"],
  ["cursor-text", "cursor"],
  ["cursor-vertical-text", "cursor"],
  ["cursor-w-resize", "cursor"],
  ["cursor-wait", "cursor"],
  ["cursor-zoom-in", "cursor"],
  ["cursor-zoom-out", "cursor"],
  ["decoration-auto", "text-decoration-thickness"],
  ["decoration-clone", "-webkit-box-decoration-break,box-decoration-break"],
  ["decoration-dashed", "text-decoration-style"],
  ["decoration-dotted", "text-decoration-style"],
  ["decoration-double", "text-decoration-style"],
  ["decoration-from-font", "text-decoration-thickness"],
  ["decoration-slice", "-webkit-box-decoration-break,box-decoration-break"],
  ["decoration-solid", "text-decoration-style"],
  ["decoration-wavy", "text-decoration-style"],
  ["diagonal-fractions", "--tw-numeric-fraction"],
  ["divide-dashed", "--tw-border-style"],
  ["divide-dotted", "--tw-border-style"],
  ["divide-double", "--tw-border-style"],
  ["divide-none", "--tw-border-style"],
  ["divide-solid", "--tw-border-style"],
  ["divide-x", "--tw-divide-x-reverse"],
  ["divide-x-reverse", "--tw-divide-x-reverse"],
  ["divide-y", "--tw-divide-y-reverse"],
  ["divide-y-reverse", "--tw-divide-y-reverse"],
  ["drop-shadow", "--tw-drop-shadow,--tw-drop-shadow-size"],
  ["drop-shadow-none", "--tw-drop-shadow"],
  ["duration-initial", "--tw-duration"],
  ["end-auto", "inset-inline-end"],
  ["end-full", "inset-inline-end"],
  ["end-px", "inset-inline-end"],
  ["field-chrome", "background-color,border-color,border-radius,border-width,color,font-size,height,line-height,padding-inline,width"],
  ["field-sizing-content", "field-sizing"],
  ["field-sizing-fixed", "field-sizing"],
  ["fill-none", "fill"],
  ["filter", "filter"],
  ["fixed", "position"],
  ["flex", "display"],
  ["flex-auto", "flex"],
  ["flex-col", "flex-direction"],
  ["flex-col-reverse", "flex-direction"],
  ["flex-grow", "flex-grow"],
  ["flex-initial", "flex"],
  ["flex-none", "flex"],
  ["flex-nowrap", "flex-wrap"],
  ["flex-row", "flex-direction"],
  ["flex-row-reverse", "flex-direction"],
  ["flex-shrink", "flex-shrink"],
  ["flex-wrap", "flex-wrap"],
  ["flex-wrap-reverse", "flex-wrap"],
  ["float-end", "float"],
  ["float-left", "float"],
  ["float-none", "float"],
  ["float-right", "float"],
  ["float-start", "float"],
  ["flow-root", "display"],
  ["focus-ring", "forge:focus-ring"],
  ["focus-ring-outset", "forge:focus-ring-outset"],
  ["font-stretch-condensed", "font-stretch"],
  ["font-stretch-expanded", "font-stretch"],
  ["font-stretch-extra-condensed", "font-stretch"],
  ["font-stretch-extra-expanded", "font-stretch"],
  ["font-stretch-normal", "font-stretch"],
  ["font-stretch-semi-condensed", "font-stretch"],
  ["font-stretch-semi-expanded", "font-stretch"],
  ["font-stretch-ultra-condensed", "font-stretch"],
  ["font-stretch-ultra-expanded", "font-stretch"],
  ["forced-color-adjust-auto", "forced-color-adjust"],
  ["forced-color-adjust-none", "forced-color-adjust"],
  ["gap-px", "gap"],
  ["gap-x-px", "column-gap"],
  ["gap-y-px", "row-gap"],
  ["grayscale", "--tw-grayscale"],
  ["grid", "display"],
  ["grid-flow-col", "grid-auto-flow"],
  ["grid-flow-col-dense", "grid-auto-flow"],
  ["grid-flow-dense", "grid-auto-flow"],
  ["grid-flow-row", "grid-auto-flow"],
  ["grid-flow-row-dense", "grid-auto-flow"],
  ["grow", "flex-grow"],
  ["h-auto", "height"],
  ["h-dvh", "height"],
  ["h-dvw", "height"],
  ["h-fit", "height"],
  ["h-full", "height"],
  ["h-lh", "height"],
  ["h-lvh", "height"],
  ["h-lvw", "height"],
  ["h-max", "height"],
  ["h-min", "height"],
  ["h-px", "height"],
  ["h-screen", "height"],
  ["h-svh", "height"],
  ["h-svw", "height"],
  ["hidden", "display"],
  ["hyphens-auto", "-webkit-hyphens,hyphens"],
  ["hyphens-manual", "-webkit-hyphens,hyphens"],
  ["hyphens-none", "-webkit-hyphens,hyphens"],
  ["indent-px", "text-indent"],
  ["inline", "display"],
  ["inline-auto", "inline-size"],
  ["inline-block", "display"],
  ["inline-dvw", "inline-size"],
  ["inline-fit", "inline-size"],
  ["inline-flex", "display"],
  ["inline-full", "inline-size"],
  ["inline-grid", "display"],
  ["inline-lvw", "inline-size"],
  ["inline-max", "inline-size"],
  ["inline-min", "inline-size"],
  ["inline-px", "inline-size"],
  ["inline-screen", "inline-size"],
  ["inline-svw", "inline-size"],
  ["inline-table", "display"],
  ["inset-auto", "inset"],
  ["inset-be-auto", "inset-block-end"],
  ["inset-be-full", "inset-block-end"],
  ["inset-be-px", "inset-block-end"],
  ["inset-bs-auto", "inset-block-start"],
  ["inset-bs-full", "inset-block-start"],
  ["inset-bs-px", "inset-block-start"],
  ["inset-e-auto", "inset-inline-end"],
  ["inset-e-full", "inset-inline-end"],
  ["inset-e-px", "inset-inline-end"],
  ["inset-full", "inset"],
  ["inset-px", "inset"],
  ["inset-ring", "--tw-inset-ring-shadow"],
  ["inset-s-auto", "inset-inline-start"],
  ["inset-s-full", "inset-inline-start"],
  ["inset-s-px", "inset-inline-start"],
  ["inset-shadow-initial", "--tw-inset-shadow-color"],
  ["inset-x-auto", "inset-inline"],
  ["inset-x-full", "inset-inline"],
  ["inset-x-px", "inset-inline"],
  ["inset-y-auto", "inset-block"],
  ["inset-y-full", "inset-block"],
  ["inset-y-px", "inset-block"],
  ["invert", "--tw-invert"],
  ["invisible", "visibility"],
  ["isolate", "isolation"],
  ["isolation-auto", "isolation"],
  ["italic", "font-style"],
  ["items-baseline", "align-items"],
  ["items-baseline-last", "align-items"],
  ["items-center", "align-items"],
  ["items-center-safe", "align-items"],
  ["items-end", "align-items"],
  ["items-end-safe", "align-items"],
  ["items-start", "align-items"],
  ["items-stretch", "align-items"],
  ["justify-around", "justify-content"],
  ["justify-baseline", "justify-content"],
  ["justify-between", "justify-content"],
  ["justify-center", "justify-content"],
  ["justify-center-safe", "justify-content"],
  ["justify-end", "justify-content"],
  ["justify-end-safe", "justify-content"],
  ["justify-evenly", "justify-content"],
  ["justify-items-center", "justify-items"],
  ["justify-items-center-safe", "justify-items"],
  ["justify-items-end", "justify-items"],
  ["justify-items-end-safe", "justify-items"],
  ["justify-items-normal", "justify-items"],
  ["justify-items-start", "justify-items"],
  ["justify-items-stretch", "justify-items"],
  ["justify-normal", "justify-content"],
  ["justify-self-auto", "justify-self"],
  ["justify-self-center", "justify-self"],
  ["justify-self-center-safe", "justify-self"],
  ["justify-self-end", "justify-self"],
  ["justify-self-end-safe", "justify-self"],
  ["justify-self-start", "justify-self"],
  ["justify-self-stretch", "justify-self"],
  ["justify-start", "justify-content"],
  ["justify-stretch", "justify-content"],
  ["leading-px", "--tw-leading"],
  ["left-auto", "left"],
  ["left-full", "left"],
  ["left-px", "left"],
  ["line-through", "text-decoration-line"],
  ["lining-nums", "--tw-numeric-figure"],
  ["list-inside", "list-style-position"],
  ["list-item", "display"],
  ["list-outside", "list-style-position"],
  ["lowercase", "text-transform"],
  ["m-auto", "margin"],
  ["m-px", "margin"],
  ["mask-add", "mask-composite"],
  ["mask-alpha", "mask-mode"],
  ["mask-auto", "mask-size"],
  ["mask-bottom", "mask-position"],
  ["mask-bottom-left", "mask-position"],
  ["mask-bottom-right", "mask-position"],
  ["mask-center", "mask-position"],
  ["mask-circle", "--tw-mask-radial-shape"],
  ["mask-clip-border", "mask-clip"],
  ["mask-clip-content", "mask-clip"],
  ["mask-clip-fill", "mask-clip"],
  ["mask-clip-padding", "mask-clip"],
  ["mask-clip-stroke", "mask-clip"],
  ["mask-clip-view", "mask-clip"],
  ["mask-contain", "mask-size"],
  ["mask-cover", "mask-size"],
  ["mask-ellipse", "--tw-mask-radial-shape"],
  ["mask-exclude", "mask-composite"],
  ["mask-intersect", "mask-composite"],
  ["mask-left", "mask-position"],
  ["mask-luminance", "mask-mode"],
  ["mask-match", "mask-mode"],
  ["mask-no-clip", "mask-clip"],
  ["mask-no-repeat", "mask-repeat"],
  ["mask-none", "mask-image"],
  ["mask-origin-border", "mask-origin"],
  ["mask-origin-content", "mask-origin"],
  ["mask-origin-fill", "mask-origin"],
  ["mask-origin-padding", "mask-origin"],
  ["mask-origin-stroke", "mask-origin"],
  ["mask-origin-view", "mask-origin"],
  ["mask-radial-at-bottom", "--tw-mask-radial-position"],
  ["mask-radial-at-bottom-left", "--tw-mask-radial-position"],
  ["mask-radial-at-bottom-right", "--tw-mask-radial-position"],
  ["mask-radial-at-center", "--tw-mask-radial-position"],
  ["mask-radial-at-left", "--tw-mask-radial-position"],
  ["mask-radial-at-right", "--tw-mask-radial-position"],
  ["mask-radial-at-top", "--tw-mask-radial-position"],
  ["mask-radial-at-top-left", "--tw-mask-radial-position"],
  ["mask-radial-at-top-right", "--tw-mask-radial-position"],
  ["mask-radial-closest-corner", "--tw-mask-radial-size"],
  ["mask-radial-closest-side", "--tw-mask-radial-size"],
  ["mask-radial-farthest-corner", "--tw-mask-radial-size"],
  ["mask-radial-farthest-side", "--tw-mask-radial-size"],
  ["mask-repeat", "mask-repeat"],
  ["mask-repeat-round", "mask-repeat"],
  ["mask-repeat-space", "mask-repeat"],
  ["mask-repeat-x", "mask-repeat"],
  ["mask-repeat-y", "mask-repeat"],
  ["mask-right", "mask-position"],
  ["mask-subtract", "mask-composite"],
  ["mask-top", "mask-position"],
  ["mask-top-left", "mask-position"],
  ["mask-top-right", "mask-position"],
  ["mask-type-alpha", "mask-type"],
  ["mask-type-luminance", "mask-type"],
  ["max-block-dvh", "max-block-size"],
  ["max-block-fit", "max-block-size"],
  ["max-block-full", "max-block-size"],
  ["max-block-lh", "max-block-size"],
  ["max-block-lvh", "max-block-size"],
  ["max-block-max", "max-block-size"],
  ["max-block-min", "max-block-size"],
  ["max-block-none", "max-block-size"],
  ["max-block-px", "max-block-size"],
  ["max-block-screen", "max-block-size"],
  ["max-block-svh", "max-block-size"],
  ["max-h-dvh", "max-height"],
  ["max-h-dvw", "max-height"],
  ["max-h-fit", "max-height"],
  ["max-h-full", "max-height"],
  ["max-h-lh", "max-height"],
  ["max-h-lvh", "max-height"],
  ["max-h-lvw", "max-height"],
  ["max-h-max", "max-height"],
  ["max-h-min", "max-height"],
  ["max-h-none", "max-height"],
  ["max-h-px", "max-height"],
  ["max-h-screen", "max-height"],
  ["max-h-svh", "max-height"],
  ["max-h-svw", "max-height"],
  ["max-inline-dvw", "max-inline-size"],
  ["max-inline-fit", "max-inline-size"],
  ["max-inline-full", "max-inline-size"],
  ["max-inline-lvw", "max-inline-size"],
  ["max-inline-max", "max-inline-size"],
  ["max-inline-min", "max-inline-size"],
  ["max-inline-none", "max-inline-size"],
  ["max-inline-px", "max-inline-size"],
  ["max-inline-screen", "max-inline-size"],
  ["max-inline-svw", "max-inline-size"],
  ["max-w-dvh", "max-width"],
  ["max-w-dvw", "max-width"],
  ["max-w-fit", "max-width"],
  ["max-w-full", "max-width"],
  ["max-w-lvh", "max-width"],
  ["max-w-lvw", "max-width"],
  ["max-w-max", "max-width"],
  ["max-w-min", "max-width"],
  ["max-w-none", "max-width"],
  ["max-w-px", "max-width"],
  ["max-w-screen", "max-width"],
  ["max-w-svh", "max-width"],
  ["max-w-svw", "max-width"],
  ["mb-auto", "margin-bottom"],
  ["mb-px", "margin-bottom"],
  ["mbe-auto", "margin-block-end"],
  ["mbe-px", "margin-block-end"],
  ["mbs-auto", "margin-block-start"],
  ["mbs-px", "margin-block-start"],
  ["me-auto", "margin-inline-end"],
  ["me-px", "margin-inline-end"],
  ["min-block-auto", "min-block-size"],
  ["min-block-dvh", "min-block-size"],
  ["min-block-fit", "min-block-size"],
  ["min-block-full", "min-block-size"],
  ["min-block-lh", "min-block-size"],
  ["min-block-lvh", "min-block-size"],
  ["min-block-max", "min-block-size"],
  ["min-block-min", "min-block-size"],
  ["min-block-px", "min-block-size"],
  ["min-block-screen", "min-block-size"],
  ["min-block-svh", "min-block-size"],
  ["min-h-auto", "min-height"],
  ["min-h-dvh", "min-height"],
  ["min-h-dvw", "min-height"],
  ["min-h-fit", "min-height"],
  ["min-h-full", "min-height"],
  ["min-h-lh", "min-height"],
  ["min-h-lvh", "min-height"],
  ["min-h-lvw", "min-height"],
  ["min-h-max", "min-height"],
  ["min-h-min", "min-height"],
  ["min-h-px", "min-height"],
  ["min-h-screen", "min-height"],
  ["min-h-svh", "min-height"],
  ["min-h-svw", "min-height"],
  ["min-inline-auto", "min-inline-size"],
  ["min-inline-dvw", "min-inline-size"],
  ["min-inline-fit", "min-inline-size"],
  ["min-inline-full", "min-inline-size"],
  ["min-inline-lvw", "min-inline-size"],
  ["min-inline-max", "min-inline-size"],
  ["min-inline-min", "min-inline-size"],
  ["min-inline-px", "min-inline-size"],
  ["min-inline-screen", "min-inline-size"],
  ["min-inline-svw", "min-inline-size"],
  ["min-w-auto", "min-width"],
  ["min-w-dvh", "min-width"],
  ["min-w-dvw", "min-width"],
  ["min-w-fit", "min-width"],
  ["min-w-full", "min-width"],
  ["min-w-lvh", "min-width"],
  ["min-w-lvw", "min-width"],
  ["min-w-max", "min-width"],
  ["min-w-min", "min-width"],
  ["min-w-px", "min-width"],
  ["min-w-screen", "min-width"],
  ["min-w-svh", "min-width"],
  ["min-w-svw", "min-width"],
  ["mix-blend-color", "mix-blend-mode"],
  ["mix-blend-color-burn", "mix-blend-mode"],
  ["mix-blend-color-dodge", "mix-blend-mode"],
  ["mix-blend-darken", "mix-blend-mode"],
  ["mix-blend-difference", "mix-blend-mode"],
  ["mix-blend-exclusion", "mix-blend-mode"],
  ["mix-blend-hard-light", "mix-blend-mode"],
  ["mix-blend-hue", "mix-blend-mode"],
  ["mix-blend-lighten", "mix-blend-mode"],
  ["mix-blend-luminosity", "mix-blend-mode"],
  ["mix-blend-multiply", "mix-blend-mode"],
  ["mix-blend-normal", "mix-blend-mode"],
  ["mix-blend-overlay", "mix-blend-mode"],
  ["mix-blend-plus-darker", "mix-blend-mode"],
  ["mix-blend-plus-lighter", "mix-blend-mode"],
  ["mix-blend-saturation", "mix-blend-mode"],
  ["mix-blend-screen", "mix-blend-mode"],
  ["mix-blend-soft-light", "mix-blend-mode"],
  ["ml-auto", "margin-left"],
  ["ml-px", "margin-left"],
  ["mr-auto", "margin-right"],
  ["mr-px", "margin-right"],
  ["ms-auto", "margin-inline-start"],
  ["ms-px", "margin-inline-start"],
  ["mt-auto", "margin-top"],
  ["mt-px", "margin-top"],
  ["mx-auto", "margin-inline"],
  ["mx-px", "margin-inline"],
  ["my-auto", "margin-block"],
  ["my-px", "margin-block"],
  ["no-underline", "text-decoration-line"],
  ["normal-case", "text-transform"],
  ["normal-nums", "font-variant-numeric"],
  ["not-italic", "font-style"],
  ["not-sr-only", "sr-only"],
  ["object-contain", "object-fit"],
  ["object-cover", "object-fit"],
  ["object-fill", "object-fit"],
  ["object-left-bottom", "object-position"],
  ["object-left-top", "object-position"],
  ["object-none", "object-fit"],
  ["object-right-bottom", "object-position"],
  ["object-right-top", "object-position"],
  ["object-scale-down", "object-fit"],
  ["oldstyle-nums", "--tw-numeric-figure"],
  ["order-none", "order"],
  ["ordinal", "--tw-ordinal"],
  ["otp-cells", "background-image,background-position,background-repeat,background-size,width"],
  ["otp-editor", "box-sizing,letter-spacing,padding-inline,width"],
  ["outline", "outline-style,outline-width"],
  ["outline-dashed", "--tw-outline-style"],
  ["outline-dotted", "--tw-outline-style"],
  ["outline-double", "--tw-outline-style"],
  ["outline-hidden", "--tw-outline-style"],
  ["outline-none", "--tw-outline-style"],
  ["outline-solid", "--tw-outline-style"],
  ["overflow-auto", "overflow"],
  ["overflow-clip", "overflow"],
  ["overflow-ellipsis", "text-overflow"],
  ["overflow-hidden", "overflow"],
  ["overflow-scroll", "overflow"],
  ["overflow-visible", "overflow"],
  ["overflow-x-auto", "overflow-x"],
  ["overflow-x-clip", "overflow-x"],
  ["overflow-x-hidden", "overflow-x"],
  ["overflow-x-scroll", "overflow-x"],
  ["overflow-x-visible", "overflow-x"],
  ["overflow-y-auto", "overflow-y"],
  ["overflow-y-clip", "overflow-y"],
  ["overflow-y-hidden", "overflow-y"],
  ["overflow-y-scroll", "overflow-y"],
  ["overflow-y-visible", "overflow-y"],
  ["overline", "text-decoration-line"],
  ["overscroll-auto", "overscroll-behavior"],
  ["overscroll-contain", "overscroll-behavior"],
  ["overscroll-none", "overscroll-behavior"],
  ["overscroll-x-auto", "overscroll-behavior-x"],
  ["overscroll-x-contain", "overscroll-behavior-x"],
  ["overscroll-x-none", "overscroll-behavior-x"],
  ["overscroll-y-auto", "overscroll-behavior-y"],
  ["overscroll-y-contain", "overscroll-behavior-y"],
  ["overscroll-y-none", "overscroll-behavior-y"],
  ["p-px", "padding"],
  ["pb-px", "padding-bottom"],
  ["pbe-px", "padding-block-end"],
  ["pbs-px", "padding-block-start"],
  ["pe-px", "padding-inline-end"],
  ["pl-px", "padding-left"],
  ["place-content-around", "place-content"],
  ["place-content-baseline", "place-content"],
  ["place-content-between", "place-content"],
  ["place-content-center", "place-content"],
  ["place-content-center-safe", "place-content"],
  ["place-content-end", "place-content"],
  ["place-content-end-safe", "place-content"],
  ["place-content-evenly", "place-content"],
  ["place-content-start", "place-content"],
  ["place-content-stretch", "place-content"],
  ["place-items-baseline", "place-items"],
  ["place-items-center", "place-items"],
  ["place-items-center-safe", "place-items"],
  ["place-items-end", "place-items"],
  ["place-items-end-safe", "place-items"],
  ["place-items-start", "place-items"],
  ["place-items-stretch", "place-items"],
  ["place-self-auto", "place-self"],
  ["place-self-center", "place-self"],
  ["place-self-center-safe", "place-self"],
  ["place-self-end", "place-self"],
  ["place-self-end-safe", "place-self"],
  ["place-self-start", "place-self"],
  ["place-self-stretch", "place-self"],
  ["pointer-events-auto", "pointer-events"],
  ["pointer-events-none", "pointer-events"],
  ["pr-px", "padding-right"],
  ["proportional-nums", "--tw-numeric-spacing"],
  ["ps-px", "padding-inline-start"],
  ["pt-px", "padding-top"],
  ["px-px", "padding-inline"],
  ["py-px", "padding-block"],
  ["relative", "position"],
  ["resize", "resize"],
  ["resize-none", "resize"],
  ["resize-x", "resize"],
  ["resize-y", "resize"],
  ["right-auto", "right"],
  ["right-full", "right"],
  ["right-px", "right"],
  ["ring", "--tw-ring-shadow"],
  ["ring-inset", "--tw-ring-inset"],
  ["rotate-none", "rotate"],
  ["rounded", "border-radius"],
  ["rounded-b", "border-bottom-left-radius,border-bottom-right-radius"],
  ["rounded-bl", "border-bottom-left-radius"],
  ["rounded-br", "border-bottom-right-radius"],
  ["rounded-e", "border-end-end-radius,border-start-end-radius"],
  ["rounded-ee", "border-end-end-radius"],
  ["rounded-es", "border-end-start-radius"],
  ["rounded-l", "border-bottom-left-radius,border-top-left-radius"],
  ["rounded-r", "border-bottom-right-radius,border-top-right-radius"],
  ["rounded-s", "border-end-start-radius,border-start-start-radius"],
  ["rounded-se", "border-start-end-radius"],
  ["rounded-ss", "border-start-start-radius"],
  ["rounded-t", "border-top-left-radius,border-top-right-radius"],
  ["rounded-tl", "border-top-left-radius"],
  ["rounded-tr", "border-top-right-radius"],
  ["scale-3d", "scale"],
  ["scale-none", "scale"],
  ["scheme-dark", "color-scheme"],
  ["scheme-light", "color-scheme"],
  ["scheme-light-dark", "color-scheme"],
  ["scheme-normal", "color-scheme"],
  ["scheme-only-dark", "color-scheme"],
  ["scheme-only-light", "color-scheme"],
  ["scroll-auto", "scroll-behavior"],
  ["scroll-m-px", "scroll-margin"],
  ["scroll-mb-px", "scroll-margin-bottom"],
  ["scroll-mbe-px", "scroll-margin-block-end"],
  ["scroll-mbs-px", "scroll-margin-block-start"],
  ["scroll-me-px", "scroll-margin-inline-end"],
  ["scroll-ml-px", "scroll-margin-left"],
  ["scroll-mr-px", "scroll-margin-right"],
  ["scroll-ms-px", "scroll-margin-inline-start"],
  ["scroll-mt-px", "scroll-margin-top"],
  ["scroll-mx-px", "scroll-margin-inline"],
  ["scroll-my-px", "scroll-margin-block"],
  ["scroll-p-px", "scroll-padding"],
  ["scroll-pb-px", "scroll-padding-bottom"],
  ["scroll-pbe-px", "scroll-padding-block-end"],
  ["scroll-pbs-px", "scroll-padding-block-start"],
  ["scroll-pe-px", "scroll-padding-inline-end"],
  ["scroll-pl-px", "scroll-padding-left"],
  ["scroll-pr-px", "scroll-padding-right"],
  ["scroll-ps-px", "scroll-padding-inline-start"],
  ["scroll-pt-px", "scroll-padding-top"],
  ["scroll-px-px", "scroll-padding-inline"],
  ["scroll-py-px", "scroll-padding-block"],
  ["scroll-smooth", "scroll-behavior"],
  ["scrollbar-auto", "scrollbar-width"],
  ["scrollbar-gutter-auto", "scrollbar-gutter"],
  ["scrollbar-gutter-both", "scrollbar-gutter"],
  ["scrollbar-gutter-stable", "scrollbar-gutter"],
  ["scrollbar-none", "scrollbar-width"],
  ["scrollbar-thin", "scrollbar-width"],
  ["select-all", "-webkit-user-select,user-select"],
  ["select-auto", "-webkit-user-select,user-select"],
  ["select-none", "-webkit-user-select,user-select"],
  ["select-text", "-webkit-user-select,user-select"],
  ["self-auto", "align-self"],
  ["self-baseline", "align-self"],
  ["self-baseline-last", "align-self"],
  ["self-center", "align-self"],
  ["self-center-safe", "align-self"],
  ["self-end", "align-self"],
  ["self-end-safe", "align-self"],
  ["self-start", "align-self"],
  ["self-stretch", "align-self"],
  ["sepia", "--tw-sepia"],
  ["shadow", "--tw-shadow"],
  ["shadow-initial", "--tw-shadow-color"],
  ["shrink", "flex-shrink"],
  ["size-auto", "height,width"],
  ["size-dvh", "height,width"],
  ["size-dvw", "height,width"],
  ["size-fit", "height,width"],
  ["size-full", "height,width"],
  ["size-lvh", "height,width"],
  ["size-lvw", "height,width"],
  ["size-max", "height,width"],
  ["size-min", "height,width"],
  ["size-px", "height,width"],
  ["size-svh", "height,width"],
  ["size-svw", "height,width"],
  ["slashed-zero", "--tw-slashed-zero"],
  ["snap-align-none", "scroll-snap-align"],
  ["snap-always", "scroll-snap-stop"],
  ["snap-both", "scroll-snap-type"],
  ["snap-center", "scroll-snap-align"],
  ["snap-end", "scroll-snap-align"],
  ["snap-mandatory", "--tw-scroll-snap-strictness"],
  ["snap-none", "scroll-snap-type"],
  ["snap-normal", "scroll-snap-stop"],
  ["snap-proximity", "--tw-scroll-snap-strictness"],
  ["snap-start", "scroll-snap-align"],
  ["snap-x", "scroll-snap-type"],
  ["snap-y", "scroll-snap-type"],
  ["space-x-px", "--tw-space-x-reverse"],
  ["space-x-reverse", "--tw-space-x-reverse"],
  ["space-y-px", "--tw-space-y-reverse"],
  ["space-y-reverse", "--tw-space-y-reverse"],
  ["sr-only", "sr-only"],
  ["stacked-fractions", "--tw-numeric-fraction"],
  ["start-auto", "inset-inline-start"],
  ["start-full", "inset-inline-start"],
  ["start-px", "inset-inline-start"],
  ["state-busy", "forge:state-busy"],
  ["state-disabled", "forge:state-disabled"],
  ["state-invalid", "forge:state-invalid"],
  ["static", "position"],
  ["sticky", "position"],
  ["stroke-none", "stroke"],
  ["subpixel-antialiased", "-moz-osx-font-smoothing,-webkit-font-smoothing"],
  ["table", "display"],
  ["table-auto", "table-layout"],
  ["table-caption", "display"],
  ["table-cell", "display"],
  ["table-column", "display"],
  ["table-column-group", "display"],
  ["table-fixed", "table-layout"],
  ["table-footer-group", "display"],
  ["table-header-group", "display"],
  ["table-row", "display"],
  ["table-row-group", "display"],
  ["tabular-nums", "--tw-numeric-spacing"],
  ["text-balance", "text-wrap"],
  ["text-center", "text-align"],
  ["text-clip", "text-overflow"],
  ["text-ellipsis", "text-overflow"],
  ["text-end", "text-align"],
  ["text-justify", "text-align"],
  ["text-left", "text-align"],
  ["text-nowrap", "text-wrap"],
  ["text-pretty", "text-wrap"],
  ["text-right", "text-align"],
  ["text-shadow-initial", "--tw-text-shadow-color"],
  ["text-start", "text-align"],
  ["text-wrap", "text-wrap"],
  ["top-auto", "top"],
  ["top-full", "top"],
  ["top-px", "top"],
  ["touch-auto", "touch-action"],
  ["touch-manipulation", "touch-action"],
  ["touch-none", "touch-action"],
  ["touch-pan-down", "--tw-pan-y"],
  ["touch-pan-left", "--tw-pan-x"],
  ["touch-pan-right", "--tw-pan-x"],
  ["touch-pan-up", "--tw-pan-y"],
  ["touch-pan-x", "--tw-pan-x"],
  ["touch-pan-y", "--tw-pan-y"],
  ["touch-pinch-zoom", "--tw-pinch-zoom"],
  ["transform", "transform"],
  ["transform-3d", "transform-style"],
  ["transform-border", "transform-box"],
  ["transform-content", "transform-box"],
  ["transform-cpu", "transform"],
  ["transform-fill", "transform-box"],
  ["transform-flat", "transform-style"],
  ["transform-gpu", "transform"],
  ["transform-none", "transform"],
  ["transform-stroke", "transform-box"],
  ["transform-view", "transform-box"],
  ["transition", "transition-duration,transition-property,transition-timing-function"],
  ["transition-discrete", "transition-behavior"],
  ["transition-normal", "transition-behavior"],
  ["translate-3d", "translate"],
  ["translate-full", "--tw-translate-x,--tw-translate-y"],
  ["translate-none", "translate"],
  ["translate-px", "--tw-translate-x,--tw-translate-y"],
  ["translate-x-full", "--tw-translate-x"],
  ["translate-x-px", "--tw-translate-x"],
  ["translate-y-full", "--tw-translate-y"],
  ["translate-y-px", "--tw-translate-y"],
  ["translate-z-px", "--tw-translate-z"],
  ["truncate", "overflow,text-overflow,white-space"],
  ["underline", "text-decoration-line"],
  ["uppercase", "text-transform"],
  ["via-none", "--tw-gradient-via-stops"],
  ["visible", "visibility"],
  ["w-auto", "width"],
  ["w-dvh", "width"],
  ["w-dvw", "width"],
  ["w-fit", "width"],
  ["w-full", "width"],
  ["w-lvh", "width"],
  ["w-lvw", "width"],
  ["w-max", "width"],
  ["w-min", "width"],
  ["w-px", "width"],
  ["w-screen", "width"],
  ["w-svh", "width"],
  ["w-svw", "width"],
  ["whitespace-break-spaces", "white-space"],
  ["whitespace-normal", "white-space"],
  ["whitespace-nowrap", "white-space"],
  ["whitespace-pre", "white-space"],
  ["whitespace-pre-line", "white-space"],
  ["whitespace-pre-wrap", "white-space"],
  ["will-change-auto", "will-change"],
  ["will-change-contents", "will-change"],
  ["will-change-scroll", "will-change"],
  ["will-change-transform", "will-change"],
  ["wrap-anywhere", "overflow-wrap"],
  ["wrap-break-word", "overflow-wrap"],
  ["wrap-normal", "overflow-wrap"],
]);

const VALUE_SETS: readonly (readonly string[])[] = [
  ["0", "2", "4", "8"],
  ["0", "1", "2"],
  ["2xl", "lg", "md", "sm", "xl", "xs"],
  ["mono", "sans", "serif"],
  [
    "0%",
    "10%",
    "100%",
    "15%",
    "20%",
    "25%",
    "30%",
    "35%",
    "40%",
    "45%",
    "5%",
    "50%",
    "55%",
    "60%",
    "65%",
    "70%",
    "75%",
    "80%",
    "85%",
    "90%",
    "95%",
  ],
  ["0", "1", "2", "4", "8"],
  ["2xs", "none", "sm", "xs"],
  [
    "0",
    "0%",
    "0.5",
    "1",
    "1.5",
    "10",
    "10%",
    "100%",
    "11",
    "12",
    "14",
    "15%",
    "16",
    "2",
    "2.5",
    "20",
    "20%",
    "24",
    "25%",
    "28",
    "3",
    "3.5",
    "30%",
    "32",
    "35%",
    "36",
    "4",
    "40",
    "40%",
    "44",
    "45%",
    "48",
    "5",
    "5%",
    "50%",
    "52",
    "55%",
    "56",
    "6",
    "60",
    "60%",
    "64",
    "65%",
    "7",
    "70%",
    "72",
    "75%",
    "8",
    "80",
    "80%",
    "85%",
    "9",
    "90%",
    "95%",
    "96",
  ],
  ["2xl", "2xs", "inner", "lg", "md", "none", "sm", "xl", "xs"],
  ["0", "1", "2", "3"],
  ["2xl", "3xl", "4xl", "5xl", "6xl", "7xl", "8xl", "9xl", "base", "lg", "sm", "xl", "xs"],
  ["2xs", "lg", "md", "none", "sm", "xs"],
  ["none"],
];

const ROOT_GROUPS: ReadonlyMap<string, RootRow> = new Map<string, RootRow>([
  ["@container", { n: "container-type", a: "container-type" }],
  ["accent", { n: "accent-color", a: "accent-color" }],
  ["align", { a: "vertical-align" }],
  ["animate", { n: "animation", a: "animation" }],
  ["aspect", { n: "aspect-ratio", a: "aspect-ratio" }],
  ["auto-cols", { n: "grid-auto-columns", a: "grid-auto-columns" }],
  ["auto-rows", { n: "grid-auto-rows", a: "grid-auto-rows" }],
  ["backdrop-blur", { n: "--tw-backdrop-blur", a: "--tw-backdrop-blur" }],
  ["backdrop-brightness", { n: "--tw-backdrop-brightness", a: "--tw-backdrop-brightness" }],
  ["backdrop-contrast", { n: "--tw-backdrop-contrast", a: "--tw-backdrop-contrast" }],
  ["backdrop-filter", { a: "-webkit-backdrop-filter,backdrop-filter" }],
  ["backdrop-grayscale", { n: "--tw-backdrop-grayscale", a: "--tw-backdrop-grayscale" }],
  ["backdrop-hue-rotate", { n: "--tw-backdrop-hue-rotate", a: "--tw-backdrop-hue-rotate" }],
  ["backdrop-invert", { n: "--tw-backdrop-invert", a: "--tw-backdrop-invert" }],
  ["backdrop-opacity", { n: "--tw-backdrop-opacity", a: "--tw-backdrop-opacity" }],
  ["backdrop-saturate", { n: "--tw-backdrop-saturate", a: "--tw-backdrop-saturate" }],
  ["backdrop-sepia", { n: "--tw-backdrop-sepia", a: "--tw-backdrop-sepia" }],
  ["basis", { n: "flex-basis", a: "flex-basis" }],
  [
    "bg",
    {
      n: "background-color",
      a: "background-color",
      k: { length: "background-position", percentage: "background-position", url: "background-image" },
    },
  ],
  ["bg-conic", { n: "--tw-gradient-position", a: "--tw-gradient-position" }],
  ["bg-linear", { n: "--tw-gradient-position", a: "--tw-gradient-position" }],
  ["bg-position", { a: "background-position" }],
  ["bg-radial", { a: "--tw-gradient-position" }],
  ["bg-size", { a: "background-size" }],
  ["block", { n: "block-size", a: "block-size" }],
  ["blur", { n: "--tw-blur", a: "--tw-blur" }],
  [
    "border",
    {
      n: "border-color",
      x: [0, "border-style,border-width"],
      a: "border-color",
      k: { length: "border-style,border-width", number: "border-style,border-width" },
    },
  ],
  [
    "border-b",
    {
      n: "border-bottom-color",
      x: [0, "border-bottom-style,border-bottom-width"],
      a: "border-bottom-color",
      k: { length: "border-bottom-style,border-bottom-width", number: "border-bottom-style,border-bottom-width" },
    },
  ],
  [
    "border-be",
    {
      n: "border-block-end-color",
      x: [0, "border-block-end-style,border-block-end-width"],
      a: "border-block-end-color",
      k: { length: "border-block-end-style,border-block-end-width", number: "border-block-end-style,border-block-end-width" },
    },
  ],
  [
    "border-bs",
    {
      n: "border-block-start-color",
      x: [0, "border-block-start-style,border-block-start-width"],
      a: "border-block-start-color",
      k: { length: "border-block-start-style,border-block-start-width", number: "border-block-start-style,border-block-start-width" },
    },
  ],
  [
    "border-e",
    {
      n: "border-inline-end-color",
      x: [0, "border-inline-end-style,border-inline-end-width"],
      a: "border-inline-end-color",
      k: { length: "border-inline-end-style,border-inline-end-width", number: "border-inline-end-style,border-inline-end-width" },
    },
  ],
  [
    "border-l",
    {
      n: "border-left-color",
      x: [0, "border-left-style,border-left-width"],
      a: "border-left-color",
      k: { length: "border-left-style,border-left-width", number: "border-left-style,border-left-width" },
    },
  ],
  [
    "border-r",
    {
      n: "border-right-color",
      x: [0, "border-right-style,border-right-width"],
      a: "border-right-color",
      k: { length: "border-right-style,border-right-width", number: "border-right-style,border-right-width" },
    },
  ],
  [
    "border-s",
    {
      n: "border-inline-start-color",
      x: [0, "border-inline-start-style,border-inline-start-width"],
      a: "border-inline-start-color",
      k: { length: "border-inline-start-style,border-inline-start-width", number: "border-inline-start-style,border-inline-start-width" },
    },
  ],
  ["border-spacing", { n: "--tw-border-spacing-x,--tw-border-spacing-y", a: "--tw-border-spacing-x,--tw-border-spacing-y" }],
  ["border-spacing-x", { n: "--tw-border-spacing-x", a: "--tw-border-spacing-x" }],
  ["border-spacing-y", { n: "--tw-border-spacing-y", a: "--tw-border-spacing-y" }],
  [
    "border-t",
    {
      n: "border-top-color",
      x: [0, "border-top-style,border-top-width"],
      a: "border-top-color",
      k: { length: "border-top-style,border-top-width", number: "border-top-style,border-top-width" },
    },
  ],
  [
    "border-x",
    {
      n: "border-inline-color",
      x: [0, "border-inline-style,border-inline-width"],
      a: "border-inline-color",
      k: { length: "border-inline-style,border-inline-width", number: "border-inline-style,border-inline-width" },
    },
  ],
  [
    "border-y",
    {
      n: "border-block-color",
      x: [0, "border-block-style,border-block-width"],
      a: "border-block-color",
      k: { length: "border-block-style,border-block-width", number: "border-block-style,border-block-width" },
    },
  ],
  ["bottom", { n: "bottom", a: "bottom" }],
  ["brightness", { n: "--tw-brightness", a: "--tw-brightness" }],
  ["caret", { n: "caret-color", a: "caret-color" }],
  ["col", { n: "grid-column", a: "grid-column" }],
  ["col-end", { n: "grid-column-end", a: "grid-column-end" }],
  ["col-span", { n: "grid-column", a: "grid-column" }],
  ["col-start", { n: "grid-column-start", a: "grid-column-start" }],
  ["columns", { n: "columns", a: "columns" }],
  ["contain", { a: "contain" }],
  ["content", { a: "--tw-content" }],
  ["contrast", { n: "--tw-contrast", a: "--tw-contrast" }],
  ["cursor", { a: "cursor" }],
  [
    "decoration",
    {
      n: "text-decoration-color",
      x: [1, "text-decoration-thickness"],
      a: "text-decoration-color",
      k: { length: "text-decoration-thickness", percentage: "text-decoration-thickness" },
    },
  ],
  ["delay", { n: "transition-delay", a: "transition-delay" }],
  ["divide", { n: "border-color", a: "border-color" }],
  ["divide-x", { n: "--tw-divide-x-reverse", a: "--tw-divide-x-reverse" }],
  ["divide-y", { n: "--tw-divide-y-reverse", a: "--tw-divide-y-reverse" }],
  [
    "drop-shadow",
    {
      n: "--tw-drop-shadow,--tw-drop-shadow-color",
      x: [2, "--tw-drop-shadow,--tw-drop-shadow-size"],
      a: "--tw-drop-shadow,--tw-drop-shadow-size",
      k: { color: "--tw-drop-shadow,--tw-drop-shadow-color" },
    },
  ],
  ["duration", { n: "--tw-duration", a: "--tw-duration" }],
  ["ease", { n: "--tw-ease", a: "--tw-ease" }],
  ["end", { n: "inset-inline-end", a: "inset-inline-end" }],
  ["fill", { n: "fill", a: "fill" }],
  ["filter", { a: "filter" }],
  ["flex", { n: "flex", a: "flex" }],
  ["flex-grow", { n: "flex-grow", a: "flex-grow" }],
  ["flex-shrink", { n: "flex-shrink", a: "flex-shrink" }],
  [
    "font",
    { n: "--tw-font-weight", x: [3, "font-family"], a: "--tw-font-weight", k: { color: "font-family", url: "font-family", other: "font-family" } },
  ],
  ["font-features", { a: "font-feature-settings" }],
  ["font-stretch", { n: "font-stretch", a: "font-stretch" }],
  [
    "from",
    {
      n: "--tw-gradient-from,--tw-gradient-stops",
      x: [4, "--tw-gradient-from-position"],
      a: "--tw-gradient-from,--tw-gradient-stops",
      k: { length: "--tw-gradient-from-position", percentage: "--tw-gradient-from-position" },
    },
  ],
  ["gap", { n: "gap", a: "gap" }],
  ["gap-x", { n: "column-gap", a: "column-gap" }],
  ["gap-y", { n: "row-gap", a: "row-gap" }],
  ["grayscale", { n: "--tw-grayscale", a: "--tw-grayscale" }],
  ["grid-cols", { n: "grid-template-columns", a: "grid-template-columns" }],
  ["grid-rows", { n: "grid-template-rows", a: "grid-template-rows" }],
  ["grow", { n: "flex-grow", a: "flex-grow" }],
  ["h", { n: "height", a: "height" }],
  ["hue-rotate", { n: "--tw-hue-rotate", a: "--tw-hue-rotate" }],
  ["indent", { n: "text-indent", a: "text-indent" }],
  ["inline", { n: "inline-size", a: "inline-size" }],
  ["inset", { n: "inset", a: "inset" }],
  ["inset-be", { n: "inset-block-end", a: "inset-block-end" }],
  ["inset-bs", { n: "inset-block-start", a: "inset-block-start" }],
  ["inset-e", { n: "inset-inline-end", a: "inset-inline-end" }],
  [
    "inset-ring",
    { n: "--tw-inset-ring-color", x: [5, "--tw-inset-ring-shadow"], a: "--tw-inset-ring-color", k: { length: "--tw-inset-ring-shadow" } },
  ],
  ["inset-s", { n: "inset-inline-start", a: "inset-inline-start" }],
  ["inset-shadow", { n: "--tw-inset-shadow-color", x: [6, "--tw-inset-shadow"], a: "--tw-inset-shadow", k: { color: "--tw-inset-shadow-color" } }],
  ["inset-x", { n: "inset-inline", a: "inset-inline" }],
  ["inset-y", { n: "inset-block", a: "inset-block" }],
  ["invert", { n: "--tw-invert", a: "--tw-invert" }],
  ["leading", { n: "--tw-leading", a: "--tw-leading" }],
  ["left", { n: "left", a: "left" }],
  ["line-clamp", { n: "-webkit-box-orient,-webkit-line-clamp,display,overflow", a: "-webkit-box-orient,-webkit-line-clamp,display,overflow" }],
  ["list", { n: "list-style-type", a: "list-style-type" }],
  ["list-image", { n: "list-style-image", a: "list-style-image" }],
  ["m", { n: "margin", a: "margin" }],
  ["mask", { a: "mask-image", k: { length: "mask-position", percentage: "mask-position" } }],
  [
    "mask-b-from",
    {
      n: "--tw-mask-bottom,--tw-mask-bottom-from-color,--tw-mask-linear",
      x: [7, "--tw-mask-bottom,--tw-mask-bottom-from-position,--tw-mask-linear"],
      a: "--tw-mask-bottom,--tw-mask-bottom-from-position,--tw-mask-linear",
      k: { color: "--tw-mask-bottom,--tw-mask-bottom-from-color,--tw-mask-linear" },
    },
  ],
  [
    "mask-b-to",
    {
      n: "--tw-mask-bottom,--tw-mask-bottom-to-color,--tw-mask-linear",
      x: [7, "--tw-mask-bottom,--tw-mask-bottom-to-position,--tw-mask-linear"],
      a: "--tw-mask-bottom,--tw-mask-bottom-to-position,--tw-mask-linear",
      k: { color: "--tw-mask-bottom,--tw-mask-bottom-to-color,--tw-mask-linear" },
    },
  ],
  ["mask-conic", { n: "--tw-mask-conic,--tw-mask-conic-position", a: "--tw-mask-conic,--tw-mask-conic-position" }],
  [
    "mask-conic-from",
    {
      n: "--tw-mask-conic,--tw-mask-conic-from-color,--tw-mask-conic-stops",
      x: [7, "--tw-mask-conic,--tw-mask-conic-from-position,--tw-mask-conic-stops"],
      a: "--tw-mask-conic,--tw-mask-conic-from-position,--tw-mask-conic-stops",
      k: { color: "--tw-mask-conic,--tw-mask-conic-from-color,--tw-mask-conic-stops" },
    },
  ],
  [
    "mask-conic-to",
    {
      n: "--tw-mask-conic,--tw-mask-conic-stops,--tw-mask-conic-to-color",
      x: [7, "--tw-mask-conic,--tw-mask-conic-stops,--tw-mask-conic-to-position"],
      a: "--tw-mask-conic,--tw-mask-conic-stops,--tw-mask-conic-to-position",
      k: { color: "--tw-mask-conic,--tw-mask-conic-stops,--tw-mask-conic-to-color" },
    },
  ],
  [
    "mask-l-from",
    {
      n: "--tw-mask-left,--tw-mask-left-from-color,--tw-mask-linear",
      x: [7, "--tw-mask-left,--tw-mask-left-from-position,--tw-mask-linear"],
      a: "--tw-mask-left,--tw-mask-left-from-position,--tw-mask-linear",
      k: { color: "--tw-mask-left,--tw-mask-left-from-color,--tw-mask-linear" },
    },
  ],
  [
    "mask-l-to",
    {
      n: "--tw-mask-left,--tw-mask-left-to-color,--tw-mask-linear",
      x: [7, "--tw-mask-left,--tw-mask-left-to-position,--tw-mask-linear"],
      a: "--tw-mask-left,--tw-mask-left-to-position,--tw-mask-linear",
      k: { color: "--tw-mask-left,--tw-mask-left-to-color,--tw-mask-linear" },
    },
  ],
  ["mask-linear", { n: "--tw-mask-linear,--tw-mask-linear-position", a: "--tw-mask-linear,--tw-mask-linear-position" }],
  [
    "mask-linear-from",
    {
      n: "--tw-mask-linear,--tw-mask-linear-from-color,--tw-mask-linear-stops",
      x: [7, "--tw-mask-linear,--tw-mask-linear-from-position,--tw-mask-linear-stops"],
      a: "--tw-mask-linear,--tw-mask-linear-from-position,--tw-mask-linear-stops",
      k: { color: "--tw-mask-linear,--tw-mask-linear-from-color,--tw-mask-linear-stops" },
    },
  ],
  [
    "mask-linear-to",
    {
      n: "--tw-mask-linear,--tw-mask-linear-stops,--tw-mask-linear-to-color",
      x: [7, "--tw-mask-linear,--tw-mask-linear-stops,--tw-mask-linear-to-position"],
      a: "--tw-mask-linear,--tw-mask-linear-stops,--tw-mask-linear-to-position",
      k: { color: "--tw-mask-linear,--tw-mask-linear-stops,--tw-mask-linear-to-color" },
    },
  ],
  ["mask-position", { a: "mask-position" }],
  [
    "mask-r-from",
    {
      n: "--tw-mask-linear,--tw-mask-right,--tw-mask-right-from-color",
      x: [7, "--tw-mask-linear,--tw-mask-right,--tw-mask-right-from-position"],
      a: "--tw-mask-linear,--tw-mask-right,--tw-mask-right-from-position",
      k: { color: "--tw-mask-linear,--tw-mask-right,--tw-mask-right-from-color" },
    },
  ],
  [
    "mask-r-to",
    {
      n: "--tw-mask-linear,--tw-mask-right,--tw-mask-right-to-color",
      x: [7, "--tw-mask-linear,--tw-mask-right,--tw-mask-right-to-position"],
      a: "--tw-mask-linear,--tw-mask-right,--tw-mask-right-to-position",
      k: { color: "--tw-mask-linear,--tw-mask-right,--tw-mask-right-to-color" },
    },
  ],
  ["mask-radial", { a: "--tw-mask-radial,--tw-mask-radial-size" }],
  ["mask-radial-at", { a: "--tw-mask-radial-position" }],
  [
    "mask-radial-from",
    {
      n: "--tw-mask-radial,--tw-mask-radial-from-color,--tw-mask-radial-stops",
      x: [7, "--tw-mask-radial,--tw-mask-radial-from-position,--tw-mask-radial-stops"],
      a: "--tw-mask-radial,--tw-mask-radial-from-position,--tw-mask-radial-stops",
      k: { color: "--tw-mask-radial,--tw-mask-radial-from-color,--tw-mask-radial-stops" },
    },
  ],
  [
    "mask-radial-to",
    {
      n: "--tw-mask-radial,--tw-mask-radial-stops,--tw-mask-radial-to-color",
      x: [7, "--tw-mask-radial,--tw-mask-radial-stops,--tw-mask-radial-to-position"],
      a: "--tw-mask-radial,--tw-mask-radial-stops,--tw-mask-radial-to-position",
      k: { color: "--tw-mask-radial,--tw-mask-radial-stops,--tw-mask-radial-to-color" },
    },
  ],
  ["mask-size", { a: "mask-size" }],
  [
    "mask-t-from",
    {
      n: "--tw-mask-linear,--tw-mask-top,--tw-mask-top-from-color",
      x: [7, "--tw-mask-linear,--tw-mask-top,--tw-mask-top-from-position"],
      a: "--tw-mask-linear,--tw-mask-top,--tw-mask-top-from-position",
      k: { color: "--tw-mask-linear,--tw-mask-top,--tw-mask-top-from-color" },
    },
  ],
  [
    "mask-t-to",
    {
      n: "--tw-mask-linear,--tw-mask-top,--tw-mask-top-to-color",
      x: [7, "--tw-mask-linear,--tw-mask-top,--tw-mask-top-to-position"],
      a: "--tw-mask-linear,--tw-mask-top,--tw-mask-top-to-position",
      k: { color: "--tw-mask-linear,--tw-mask-top,--tw-mask-top-to-color" },
    },
  ],
  [
    "mask-x-from",
    {
      n: "--tw-mask-left,--tw-mask-left-from-color,--tw-mask-linear,--tw-mask-right,--tw-mask-right-from-color",
      x: [7, "--tw-mask-left,--tw-mask-left-from-position,--tw-mask-linear,--tw-mask-right,--tw-mask-right-from-position"],
      a: "--tw-mask-left,--tw-mask-left-from-position,--tw-mask-linear,--tw-mask-right,--tw-mask-right-from-position",
      k: { color: "--tw-mask-left,--tw-mask-left-from-color,--tw-mask-linear,--tw-mask-right,--tw-mask-right-from-color" },
    },
  ],
  [
    "mask-x-to",
    {
      n: "--tw-mask-left,--tw-mask-left-to-color,--tw-mask-linear,--tw-mask-right,--tw-mask-right-to-color",
      x: [7, "--tw-mask-left,--tw-mask-left-to-position,--tw-mask-linear,--tw-mask-right,--tw-mask-right-to-position"],
      a: "--tw-mask-left,--tw-mask-left-to-position,--tw-mask-linear,--tw-mask-right,--tw-mask-right-to-position",
      k: { color: "--tw-mask-left,--tw-mask-left-to-color,--tw-mask-linear,--tw-mask-right,--tw-mask-right-to-color" },
    },
  ],
  [
    "mask-y-from",
    {
      n: "--tw-mask-bottom,--tw-mask-bottom-from-color,--tw-mask-linear,--tw-mask-top,--tw-mask-top-from-color",
      x: [7, "--tw-mask-bottom,--tw-mask-bottom-from-position,--tw-mask-linear,--tw-mask-top,--tw-mask-top-from-position"],
      a: "--tw-mask-bottom,--tw-mask-bottom-from-position,--tw-mask-linear,--tw-mask-top,--tw-mask-top-from-position",
      k: { color: "--tw-mask-bottom,--tw-mask-bottom-from-color,--tw-mask-linear,--tw-mask-top,--tw-mask-top-from-color" },
    },
  ],
  [
    "mask-y-to",
    {
      n: "--tw-mask-bottom,--tw-mask-bottom-to-color,--tw-mask-linear,--tw-mask-top,--tw-mask-top-to-color",
      x: [7, "--tw-mask-bottom,--tw-mask-bottom-to-position,--tw-mask-linear,--tw-mask-top,--tw-mask-top-to-position"],
      a: "--tw-mask-bottom,--tw-mask-bottom-to-position,--tw-mask-linear,--tw-mask-top,--tw-mask-top-to-position",
      k: { color: "--tw-mask-bottom,--tw-mask-bottom-to-color,--tw-mask-linear,--tw-mask-top,--tw-mask-top-to-color" },
    },
  ],
  ["max-block", { n: "max-block-size", a: "max-block-size" }],
  ["max-h", { n: "max-height", a: "max-height" }],
  ["max-inline", { n: "max-inline-size", a: "max-inline-size" }],
  ["max-w", { n: "max-width", a: "max-width" }],
  ["mb", { n: "margin-bottom", a: "margin-bottom" }],
  ["mbe", { n: "margin-block-end", a: "margin-block-end" }],
  ["mbs", { n: "margin-block-start", a: "margin-block-start" }],
  ["me", { n: "margin-inline-end", a: "margin-inline-end" }],
  ["min-block", { n: "min-block-size", a: "min-block-size" }],
  ["min-h", { n: "min-height", a: "min-height" }],
  ["min-inline", { n: "min-inline-size", a: "min-inline-size" }],
  ["min-w", { n: "min-width", a: "min-width" }],
  ["ml", { n: "margin-left", a: "margin-left" }],
  ["mr", { n: "margin-right", a: "margin-right" }],
  ["ms", { n: "margin-inline-start", a: "margin-inline-start" }],
  ["mt", { n: "margin-top", a: "margin-top" }],
  ["mx", { n: "margin-inline", a: "margin-inline" }],
  ["my", { n: "margin-block", a: "margin-block" }],
  ["object", { n: "object-position", a: "object-position" }],
  ["opacity", { n: "opacity", a: "opacity" }],
  ["order", { n: "order", a: "order" }],
  ["origin", { n: "transform-origin", a: "transform-origin" }],
  [
    "outline",
    {
      n: "outline-color",
      x: [5, "outline-style,outline-width"],
      a: "outline-color",
      k: { length: "outline-style,outline-width", number: "outline-style,outline-width", percentage: "outline-style,outline-width" },
    },
  ],
  ["outline-offset", { n: "outline-offset", a: "outline-offset" }],
  ["p", { n: "padding", a: "padding" }],
  ["pb", { n: "padding-bottom", a: "padding-bottom" }],
  ["pbe", { n: "padding-block-end", a: "padding-block-end" }],
  ["pbs", { n: "padding-block-start", a: "padding-block-start" }],
  ["pe", { n: "padding-inline-end", a: "padding-inline-end" }],
  ["perspective", { n: "perspective", a: "perspective" }],
  ["perspective-origin", { n: "perspective-origin", a: "perspective-origin" }],
  ["pl", { n: "padding-left", a: "padding-left" }],
  ["placeholder", { n: "color", a: "color" }],
  ["pr", { n: "padding-right", a: "padding-right" }],
  ["ps", { n: "padding-inline-start", a: "padding-inline-start" }],
  ["pt", { n: "padding-top", a: "padding-top" }],
  ["px", { n: "padding-inline", a: "padding-inline" }],
  ["py", { n: "padding-block", a: "padding-block" }],
  ["right", { n: "right", a: "right" }],
  ["ring", { n: "--tw-ring-color", x: [5, "--tw-ring-shadow"], a: "--tw-ring-color", k: { length: "--tw-ring-shadow" } }],
  [
    "ring-offset",
    {
      n: "--tw-ring-offset-color",
      x: [5, "--tw-ring-offset-shadow,--tw-ring-offset-width"],
      a: "--tw-ring-offset-color",
      k: { length: "--tw-ring-offset-shadow,--tw-ring-offset-width" },
    },
  ],
  ["rotate", { n: "rotate", a: "rotate" }],
  ["rotate-x", { n: "--tw-rotate-x", a: "--tw-rotate-x" }],
  ["rotate-y", { n: "--tw-rotate-y", a: "--tw-rotate-y" }],
  ["rotate-z", { n: "--tw-rotate-z", a: "--tw-rotate-z" }],
  ["rounded", { n: "border-radius", a: "border-radius" }],
  ["rounded-b", { n: "border-bottom-left-radius,border-bottom-right-radius", a: "border-bottom-left-radius,border-bottom-right-radius" }],
  ["rounded-bl", { n: "border-bottom-left-radius", a: "border-bottom-left-radius" }],
  ["rounded-br", { n: "border-bottom-right-radius", a: "border-bottom-right-radius" }],
  ["rounded-e", { n: "border-end-end-radius,border-start-end-radius", a: "border-end-end-radius,border-start-end-radius" }],
  ["rounded-ee", { n: "border-end-end-radius", a: "border-end-end-radius" }],
  ["rounded-es", { n: "border-end-start-radius", a: "border-end-start-radius" }],
  ["rounded-l", { n: "border-bottom-left-radius,border-top-left-radius", a: "border-bottom-left-radius,border-top-left-radius" }],
  ["rounded-r", { n: "border-bottom-right-radius,border-top-right-radius", a: "border-bottom-right-radius,border-top-right-radius" }],
  ["rounded-s", { n: "border-end-start-radius,border-start-start-radius", a: "border-end-start-radius,border-start-start-radius" }],
  ["rounded-se", { n: "border-start-end-radius", a: "border-start-end-radius" }],
  ["rounded-ss", { n: "border-start-start-radius", a: "border-start-start-radius" }],
  ["rounded-t", { n: "border-top-left-radius,border-top-right-radius", a: "border-top-left-radius,border-top-right-radius" }],
  ["rounded-tl", { n: "border-top-left-radius", a: "border-top-left-radius" }],
  ["rounded-tr", { n: "border-top-right-radius", a: "border-top-right-radius" }],
  ["row", { n: "grid-row", a: "grid-row" }],
  ["row-end", { n: "grid-row-end", a: "grid-row-end" }],
  ["row-span", { n: "grid-row", a: "grid-row" }],
  ["row-start", { n: "grid-row-start", a: "grid-row-start" }],
  ["saturate", { n: "--tw-saturate", a: "--tw-saturate" }],
  ["scale", { n: "--tw-scale-x,--tw-scale-y,--tw-scale-z", a: "scale" }],
  ["scale-x", { n: "--tw-scale-x", a: "--tw-scale-x" }],
  ["scale-y", { n: "--tw-scale-y", a: "--tw-scale-y" }],
  ["scale-z", { n: "--tw-scale-z", a: "--tw-scale-z" }],
  ["scroll-m", { n: "scroll-margin", a: "scroll-margin" }],
  ["scroll-mb", { n: "scroll-margin-bottom", a: "scroll-margin-bottom" }],
  ["scroll-mbe", { n: "scroll-margin-block-end", a: "scroll-margin-block-end" }],
  ["scroll-mbs", { n: "scroll-margin-block-start", a: "scroll-margin-block-start" }],
  ["scroll-me", { n: "scroll-margin-inline-end", a: "scroll-margin-inline-end" }],
  ["scroll-ml", { n: "scroll-margin-left", a: "scroll-margin-left" }],
  ["scroll-mr", { n: "scroll-margin-right", a: "scroll-margin-right" }],
  ["scroll-ms", { n: "scroll-margin-inline-start", a: "scroll-margin-inline-start" }],
  ["scroll-mt", { n: "scroll-margin-top", a: "scroll-margin-top" }],
  ["scroll-mx", { n: "scroll-margin-inline", a: "scroll-margin-inline" }],
  ["scroll-my", { n: "scroll-margin-block", a: "scroll-margin-block" }],
  ["scroll-p", { n: "scroll-padding", a: "scroll-padding" }],
  ["scroll-pb", { n: "scroll-padding-bottom", a: "scroll-padding-bottom" }],
  ["scroll-pbe", { n: "scroll-padding-block-end", a: "scroll-padding-block-end" }],
  ["scroll-pbs", { n: "scroll-padding-block-start", a: "scroll-padding-block-start" }],
  ["scroll-pe", { n: "scroll-padding-inline-end", a: "scroll-padding-inline-end" }],
  ["scroll-pl", { n: "scroll-padding-left", a: "scroll-padding-left" }],
  ["scroll-pr", { n: "scroll-padding-right", a: "scroll-padding-right" }],
  ["scroll-ps", { n: "scroll-padding-inline-start", a: "scroll-padding-inline-start" }],
  ["scroll-pt", { n: "scroll-padding-top", a: "scroll-padding-top" }],
  ["scroll-px", { n: "scroll-padding-inline", a: "scroll-padding-inline" }],
  ["scroll-py", { n: "scroll-padding-block", a: "scroll-padding-block" }],
  ["scrollbar-thumb", { n: "--tw-scrollbar-thumb", a: "--tw-scrollbar-thumb" }],
  ["scrollbar-track", { n: "--tw-scrollbar-track", a: "--tw-scrollbar-track" }],
  ["sepia", { n: "--tw-sepia", a: "--tw-sepia" }],
  ["shadow", { n: "--tw-shadow-color", x: [8, "--tw-shadow"], a: "--tw-shadow", k: { color: "--tw-shadow-color" } }],
  ["shrink", { n: "flex-shrink", a: "flex-shrink" }],
  ["size", { n: "height,width", a: "height,width" }],
  ["skew", { n: "--tw-skew-x,--tw-skew-y", a: "--tw-skew-x,--tw-skew-y" }],
  ["skew-x", { n: "--tw-skew-x", a: "--tw-skew-x" }],
  ["skew-y", { n: "--tw-skew-y", a: "--tw-skew-y" }],
  ["space-x", { n: "--tw-space-x-reverse", a: "--tw-space-x-reverse" }],
  ["space-y", { n: "--tw-space-y-reverse", a: "--tw-space-y-reverse" }],
  ["start", { n: "inset-inline-start", a: "inset-inline-start" }],
  [
    "stroke",
    { n: "stroke", x: [9, "stroke-width"], a: "stroke", k: { length: "stroke-width", number: "stroke-width", percentage: "stroke-width" } },
  ],
  ["tab", { n: "tab-size", a: "tab-size" }],
  ["text", { n: "color", x: [10, "font-size,line-height"], a: "color", k: { length: "font-size", percentage: "font-size" } }],
  ["text-shadow", { n: "--tw-text-shadow-color", x: [11, "text-shadow"], a: "text-shadow", k: { color: "--tw-text-shadow-color" } }],
  ["text-size", { n: "font-size,line-height", a: "font-size" }],
  [
    "to",
    {
      n: "--tw-gradient-stops,--tw-gradient-to",
      x: [4, "--tw-gradient-to-position"],
      a: "--tw-gradient-stops,--tw-gradient-to",
      k: { length: "--tw-gradient-to-position", percentage: "--tw-gradient-to-position" },
    },
  ],
  ["top", { n: "top", a: "top" }],
  ["tracking", { n: "--tw-tracking", a: "--tw-tracking" }],
  ["transform", { a: "transform" }],
  [
    "transition",
    {
      n: "transition-duration,transition-property,transition-timing-function",
      x: [12, "transition-property"],
      a: "transition-duration,transition-property,transition-timing-function",
    },
  ],
  ["translate", { n: "--tw-translate-x,--tw-translate-y", a: "--tw-translate-x,--tw-translate-y" }],
  ["translate-x", { n: "--tw-translate-x", a: "--tw-translate-x" }],
  ["translate-y", { n: "--tw-translate-y", a: "--tw-translate-y" }],
  ["translate-z", { n: "--tw-translate-z", a: "--tw-translate-z" }],
  ["underline-offset", { n: "text-underline-offset", a: "text-underline-offset" }],
  [
    "via",
    {
      n: "--tw-gradient-stops,--tw-gradient-via,--tw-gradient-via-stops",
      x: [4, "--tw-gradient-via-position"],
      a: "--tw-gradient-stops,--tw-gradient-via,--tw-gradient-via-stops",
      k: { length: "--tw-gradient-via-position", percentage: "--tw-gradient-via-position" },
    },
  ],
  ["w", { n: "width", a: "width" }],
  ["will-change", { a: "will-change" }],
  ["z", { n: "z-index", a: "z-index" }],
  ["zoom", { n: "zoom", a: "zoom" }],
]);

/** One-directional override edges: accepting a shorthand marks its longhands consumed, never the reverse. */
export const GROUP_OVERRIDES: ReadonlyMap<string, readonly string[]> = new Map<string, readonly string[]>([
  ["--tw-border-spacing-x,--tw-border-spacing-y", ["--tw-border-spacing-x", "--tw-border-spacing-y"]],
  ["--tw-drop-shadow,--tw-drop-shadow-color", ["--tw-drop-shadow"]],
  ["--tw-drop-shadow,--tw-drop-shadow-size", ["--tw-drop-shadow"]],
  ["--tw-gradient-stops,--tw-gradient-via,--tw-gradient-via-stops", ["--tw-gradient-via-stops"]],
  [
    "--tw-mask-bottom,--tw-mask-bottom-from-color,--tw-mask-linear,--tw-mask-top,--tw-mask-top-from-color",
    ["--tw-mask-bottom,--tw-mask-bottom-from-color,--tw-mask-linear", "--tw-mask-linear,--tw-mask-top,--tw-mask-top-from-color"],
  ],
  [
    "--tw-mask-bottom,--tw-mask-bottom-from-position,--tw-mask-linear,--tw-mask-top,--tw-mask-top-from-position",
    ["--tw-mask-bottom,--tw-mask-bottom-from-position,--tw-mask-linear", "--tw-mask-linear,--tw-mask-top,--tw-mask-top-from-position"],
  ],
  [
    "--tw-mask-bottom,--tw-mask-bottom-to-color,--tw-mask-linear,--tw-mask-top,--tw-mask-top-to-color",
    ["--tw-mask-bottom,--tw-mask-bottom-to-color,--tw-mask-linear", "--tw-mask-linear,--tw-mask-top,--tw-mask-top-to-color"],
  ],
  [
    "--tw-mask-bottom,--tw-mask-bottom-to-position,--tw-mask-linear,--tw-mask-top,--tw-mask-top-to-position",
    ["--tw-mask-bottom,--tw-mask-bottom-to-position,--tw-mask-linear", "--tw-mask-linear,--tw-mask-top,--tw-mask-top-to-position"],
  ],
  [
    "--tw-mask-left,--tw-mask-left-from-color,--tw-mask-linear,--tw-mask-right,--tw-mask-right-from-color",
    ["--tw-mask-left,--tw-mask-left-from-color,--tw-mask-linear", "--tw-mask-linear,--tw-mask-right,--tw-mask-right-from-color"],
  ],
  [
    "--tw-mask-left,--tw-mask-left-from-position,--tw-mask-linear,--tw-mask-right,--tw-mask-right-from-position",
    ["--tw-mask-left,--tw-mask-left-from-position,--tw-mask-linear", "--tw-mask-linear,--tw-mask-right,--tw-mask-right-from-position"],
  ],
  [
    "--tw-mask-left,--tw-mask-left-to-color,--tw-mask-linear,--tw-mask-right,--tw-mask-right-to-color",
    ["--tw-mask-left,--tw-mask-left-to-color,--tw-mask-linear", "--tw-mask-linear,--tw-mask-right,--tw-mask-right-to-color"],
  ],
  [
    "--tw-mask-left,--tw-mask-left-to-position,--tw-mask-linear,--tw-mask-right,--tw-mask-right-to-position",
    ["--tw-mask-left,--tw-mask-left-to-position,--tw-mask-linear", "--tw-mask-linear,--tw-mask-right,--tw-mask-right-to-position"],
  ],
  ["--tw-mask-radial,--tw-mask-radial-size", ["--tw-mask-radial-size"]],
  ["--tw-scale-x,--tw-scale-y,--tw-scale-z", ["--tw-scale-x", "--tw-scale-y", "--tw-scale-z"]],
  ["--tw-skew-x,--tw-skew-y", ["--tw-skew-x", "--tw-skew-y"]],
  ["--tw-translate-x,--tw-translate-y", ["--tw-translate-x", "--tw-translate-y"]],
  ["-webkit-box-orient,-webkit-line-clamp,display,overflow", ["display", "overflow", "overflow-x", "overflow-y"]],
  [
    "background-color,border-color,border-radius,border-width,color,font-size,height,line-height,padding-inline,width",
    [
      "background-color",
      "border-block-color",
      "border-block-end-color",
      "border-block-start-color",
      "border-bottom-color",
      "border-bottom-left-radius",
      "border-bottom-left-radius,border-bottom-right-radius",
      "border-bottom-left-radius,border-top-left-radius",
      "border-bottom-right-radius",
      "border-bottom-right-radius,border-top-right-radius",
      "border-color",
      "border-end-end-radius",
      "border-end-end-radius,border-start-end-radius",
      "border-end-start-radius",
      "border-end-start-radius,border-start-start-radius",
      "border-inline-color",
      "border-inline-end-color",
      "border-inline-start-color",
      "border-left-color",
      "border-radius",
      "border-right-color",
      "border-start-end-radius",
      "border-start-start-radius",
      "border-top-color",
      "border-top-left-radius",
      "border-top-left-radius,border-top-right-radius",
      "border-top-right-radius",
      "border-width",
      "color",
      "font-size",
      "font-size,line-height",
      "height",
      "height,width",
      "padding-inline",
      "padding-inline-end",
      "padding-inline-start",
      "padding-left",
      "padding-right",
      "width",
    ],
  ],
  [
    "background-image,background-position,background-repeat,background-size,width",
    ["background-image", "background-position", "background-repeat", "background-size", "width"],
  ],
  ["border-block-color", ["border-block-end-color", "border-block-start-color", "border-bottom-color", "border-top-color"]],
  [
    "border-block-style,border-block-width",
    [
      "border-block-end-style,border-block-end-width",
      "border-block-start-style,border-block-start-width",
      "border-bottom-style,border-bottom-width",
      "border-top-style,border-top-width",
    ],
  ],
  ["border-bottom-left-radius,border-bottom-right-radius", ["border-bottom-left-radius", "border-bottom-right-radius"]],
  ["border-bottom-left-radius,border-top-left-radius", ["border-bottom-left-radius", "border-top-left-radius"]],
  ["border-bottom-right-radius,border-top-right-radius", ["border-bottom-right-radius", "border-top-right-radius"]],
  [
    "border-color",
    [
      "border-block-color",
      "border-block-end-color",
      "border-block-start-color",
      "border-bottom-color",
      "border-inline-color",
      "border-inline-end-color",
      "border-inline-start-color",
      "border-left-color",
      "border-right-color",
      "border-top-color",
    ],
  ],
  ["border-end-end-radius,border-start-end-radius", ["border-end-end-radius", "border-start-end-radius"]],
  ["border-end-start-radius,border-start-start-radius", ["border-end-start-radius", "border-start-start-radius"]],
  ["border-inline-color", ["border-inline-end-color", "border-inline-start-color", "border-left-color", "border-right-color"]],
  [
    "border-inline-style,border-inline-width",
    [
      "border-inline-end-style,border-inline-end-width",
      "border-inline-start-style,border-inline-start-width",
      "border-left-style,border-left-width",
      "border-right-style,border-right-width",
    ],
  ],
  [
    "border-radius",
    [
      "border-bottom-left-radius",
      "border-bottom-left-radius,border-bottom-right-radius",
      "border-bottom-left-radius,border-top-left-radius",
      "border-bottom-right-radius",
      "border-bottom-right-radius,border-top-right-radius",
      "border-end-end-radius",
      "border-end-end-radius,border-start-end-radius",
      "border-end-start-radius",
      "border-end-start-radius,border-start-start-radius",
      "border-start-end-radius",
      "border-start-start-radius",
      "border-top-left-radius",
      "border-top-left-radius,border-top-right-radius",
      "border-top-right-radius",
    ],
  ],
  [
    "border-style,border-width",
    [
      "border-block-end-style,border-block-end-width",
      "border-block-start-style,border-block-start-width",
      "border-block-style,border-block-width",
      "border-bottom-style,border-bottom-width",
      "border-inline-end-style,border-inline-end-width",
      "border-inline-start-style,border-inline-start-width",
      "border-inline-style,border-inline-width",
      "border-left-style,border-left-width",
      "border-right-style,border-right-width",
      "border-top-style,border-top-width",
      "border-width",
    ],
  ],
  ["border-top-left-radius,border-top-right-radius", ["border-top-left-radius", "border-top-right-radius"]],
  [
    "box-sizing,letter-spacing,padding-inline,width",
    ["box-sizing", "padding-inline", "padding-inline-end", "padding-inline-start", "padding-left", "padding-right", "width"],
  ],
  ["flex", ["flex-basis", "flex-grow", "flex-shrink"]],
  ["font-size,line-height", ["font-size"]],
  ["gap", ["column-gap", "row-gap"]],
  ["height,width", ["height", "width"]],
  [
    "inset",
    [
      "bottom",
      "inset-block",
      "inset-block-end",
      "inset-block-start",
      "inset-inline",
      "inset-inline-end",
      "inset-inline-start",
      "left",
      "right",
      "top",
    ],
  ],
  ["inset-block", ["bottom", "inset-block-end", "inset-block-start", "top"]],
  ["inset-inline", ["inset-inline-end", "inset-inline-start", "left", "right"]],
  [
    "margin",
    [
      "margin-block",
      "margin-block-end",
      "margin-block-start",
      "margin-bottom",
      "margin-inline",
      "margin-inline-end",
      "margin-inline-start",
      "margin-left",
      "margin-right",
      "margin-top",
    ],
  ],
  ["margin-block", ["margin-block-end", "margin-block-start", "margin-bottom", "margin-top"]],
  ["margin-inline", ["margin-inline-end", "margin-inline-start", "margin-left", "margin-right"]],
  ["max-width,width", ["max-width", "width"]],
  ["overflow", ["overflow-x", "overflow-y"]],
  ["overflow,text-overflow,white-space", ["overflow", "overflow-x", "overflow-y", "text-overflow", "white-space"]],
  ["overflow-wrap,word-break", ["overflow-wrap", "word-break"]],
  ["overscroll-behavior", ["overscroll-behavior-x", "overscroll-behavior-y"]],
  [
    "padding",
    [
      "padding-block",
      "padding-block-end",
      "padding-block-start",
      "padding-bottom",
      "padding-inline",
      "padding-inline-end",
      "padding-inline-start",
      "padding-left",
      "padding-right",
      "padding-top",
    ],
  ],
  ["padding-block", ["padding-block-end", "padding-block-start", "padding-bottom", "padding-top"]],
  ["padding-inline", ["padding-inline-end", "padding-inline-start", "padding-left", "padding-right"]],
  ["place-content", ["align-content", "justify-content"]],
  ["place-items", ["align-items", "justify-items"]],
  ["place-self", ["align-self", "justify-self"]],
  [
    "scroll-margin",
    [
      "scroll-margin-block",
      "scroll-margin-block-end",
      "scroll-margin-block-start",
      "scroll-margin-bottom",
      "scroll-margin-inline",
      "scroll-margin-inline-end",
      "scroll-margin-inline-start",
      "scroll-margin-left",
      "scroll-margin-right",
      "scroll-margin-top",
    ],
  ],
  ["scroll-margin-block", ["scroll-margin-block-end", "scroll-margin-block-start", "scroll-margin-bottom", "scroll-margin-top"]],
  ["scroll-margin-inline", ["scroll-margin-inline-end", "scroll-margin-inline-start", "scroll-margin-left", "scroll-margin-right"]],
  [
    "scroll-padding",
    [
      "scroll-padding-block",
      "scroll-padding-block-end",
      "scroll-padding-block-start",
      "scroll-padding-bottom",
      "scroll-padding-inline",
      "scroll-padding-inline-end",
      "scroll-padding-inline-start",
      "scroll-padding-left",
      "scroll-padding-right",
      "scroll-padding-top",
    ],
  ],
  ["scroll-padding-block", ["scroll-padding-block-end", "scroll-padding-block-start", "scroll-padding-bottom", "scroll-padding-top"]],
  ["scroll-padding-inline", ["scroll-padding-inline-end", "scroll-padding-inline-start", "scroll-padding-left", "scroll-padding-right"]],
  ["transition-duration,transition-property,transition-timing-function", ["transition-property"]],
]);

interface RootRow {
  readonly n?: string;
  readonly x?: readonly [number, string];
  readonly a?: string;
  readonly k?: Readonly<Record<string, string>>;
}

const SETS: readonly ReadonlySet<string>[] = VALUE_SETS.map((values) => new Set(values));

const COLOR_FUNCTIONS = ["rgb(", "rgba(", "hsl(", "hsla(", "oklch(", "oklab(", "lab(", "lch(", "color(", "color-mix("];
const LENGTH = /^-?[\d.]+(?:px|rem|em|ch|ex|vw|vh|vmin|vmax|pt|pc|in|cm|mm|q)$/;
const NUMBER = /^-?[\d.]+$/;
const PERCENTAGE = /^-?[\d.]+%$/;

function arbitraryKind(value: string): string {
  const inner = value.slice(1, -1);
  const colon = inner.indexOf(":");
  if (colon !== -1) return inner.slice(0, colon);
  if (inner.startsWith("#") || COLOR_FUNCTIONS.some((fn) => inner.startsWith(fn))) return "color";
  if (inner.startsWith("url(")) return "url";
  if (LENGTH.test(inner)) return "length";
  if (PERCENTAGE.test(inner)) return "percentage";
  if (NUMBER.test(inner)) return "number";
  return "other";
}

function rootGroup(row: RootRow, value: string): string | undefined {
  if (value.startsWith("[") || value.startsWith("(")) return row.k?.[arbitraryKind(value)] ?? row.a;
  if (row.x !== undefined && (SETS[row.x[0]] as ReadonlySet<string>).has(value)) return row.x[1];
  return row.n;
}

/** Names the CSS concern a modifier-stripped utility sets, or `undefined` when it is outside the table. @internal */
export function classGroup(utility: string): string | undefined {
  if (utility.length === 0) return undefined;

  if (utility.startsWith("[")) {
    const colon = utility.indexOf(":");
    return colon === -1 ? undefined : `arb:${utility.slice(1, colon)}`;
  }

  const bare = utility.startsWith("-") ? utility.slice(1) : utility;

  const exact = STATIC_GROUPS.get(bare);
  if (exact !== undefined) return exact;

  // Longest root wins, so `text-shadow-md` is read as a shadow rather than as a colour.
  for (let i = bare.length - 1; i > 0; i -= 1) {
    if (bare[i] !== "-") continue;
    const row = ROOT_GROUPS.get(bare.slice(0, i));
    if (row !== undefined) return rootGroup(row, bare.slice(i + 1));
  }

  return undefined;
}
