import { describe, expect, it } from "bun:test";
import { chmodSync, mkdtempSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { devVarsPath, editDevVars, GENERATE_MARKER, PUSH_MARKER, parseDevVars, readDevVars, writeDevVars } from "./devvars";

const SAMPLE = `# generated by this project
${GENERATE_MARKER}
SESSION_SECRET=aaaa

# a third-party credential
STRIPE_KEY="sk_live_x"
EMPTY=
`;

describe("parseDevVars()", () => {
  it("reads every key, with its line", () => {
    expect(parseDevVars(SAMPLE).map((v) => [v.name, v.value, v.line])).toEqual([
      ["SESSION_SECRET", "aaaa", 2],
      ["STRIPE_KEY", "sk_live_x", 5],
      ["EMPTY", "", 6],
    ]);
  });

  it("marks only the key the marker precedes", () => {
    const marked = parseDevVars(SAMPLE)
      .filter((v) => v.kind === "rotatable")
      .map((v) => v.name);
    expect(marked).toEqual(["SESSION_SECRET"]);
  });

  it("does not carry the marker past the key it applied to", () => {
    const vars = parseDevVars(`${GENERATE_MARKER}\nA=1\nB=2\n`);
    expect(vars.map((v) => v.kind)).toEqual(["rotatable", "local"]);
  });

  it("ignores an ordinary comment and a line with no '='", () => {
    expect(parseDevVars("# note\njust-text\nA=1\n").map((v) => v.name)).toEqual(["A"]);
  });

  it("keeps a value containing '=' whole", () => {
    expect(parseDevVars("TOKEN=a=b=c\n")[0]?.value).toBe("a=b=c");
  });

  it("strips a matched quote pair only", () => {
    expect(parseDevVars(`A="x"\nB='y'\nC="z'\n`).map((v) => v.value)).toEqual(["x", "y", `"z'`]);
  });
});

describe("parseDevVars() — values follow dotenv, which is what wrangler pushes", () => {
  it("cuts an unquoted value at an inline comment", () => {
    expect(parseDevVars("API_KEY=abc123 # prod key\n")[0]?.value).toBe("abc123");
  });

  it("expands \\n inside double quotes", () => {
    expect(parseDevVars(`MSG="a\\nb"\n`)[0]?.value).toBe("a\nb");
  });

  it("leaves a single-quoted value literal", () => {
    expect(parseDevVars(`LIT='a\\nb'\n`)[0]?.value).toBe("a\\nb");
  });

  it("keeps a hash inside a quoted value", () => {
    expect(parseDevVars(`QUOTED="has # hash"\n`)[0]?.value).toBe("has # hash");
  });
});

describe("parseDevVars() — markers decide the kind", () => {
  it("classifies an unmarked key as local", () => {
    expect(parseDevVars("LOG_LEVEL=DEBUG\n")[0]?.kind).toBe("local");
  });

  it("classifies a secret-marked key as secret", () => {
    expect(parseDevVars(`${PUSH_MARKER}\nSTRIPE_KEY=v\n`)[0]?.kind).toBe("secret");
  });

  it("classifies a rotate-marked key as rotatable", () => {
    expect(parseDevVars(`${GENERATE_MARKER}\nSESSION_SECRET=v\n`)[0]?.kind).toBe("rotatable");
  });

  it("lets rotate win over secret, in either order", () => {
    // The two disagree about the one thing that matters — whether the local value
    // leaves this machine — so the safer claim is the one that stands.
    expect(parseDevVars(`${PUSH_MARKER}\n${GENERATE_MARKER}\nA=v\n`)[0]?.kind).toBe("rotatable");
    expect(parseDevVars(`${GENERATE_MARKER}\n${PUSH_MARKER}\nA=v\n`)[0]?.kind).toBe("rotatable");
  });

  it("clears every marker after the key it applied to", () => {
    const vars = parseDevVars(`${PUSH_MARKER}\n${GENERATE_MARKER}\nA=1\nB=2\n`);
    expect(vars.map((v) => v.kind)).toEqual(["rotatable", "local"]);
  });

  it("does not treat an ordinary comment between marker and key as a reset", () => {
    expect(parseDevVars(`${PUSH_MARKER}\n# what this key is for\nA=1\n`)[0]?.kind).toBe("secret");
  });
});

describe("editDevVars()", () => {
  it("replaces only the named value, leaving comments and markers in place", () => {
    const edited = editDevVars(SAMPLE, new Map([["SESSION_SECRET", "bbbb"]]));
    expect(edited).toBe(SAMPLE.replace("SESSION_SECRET=aaaa", "SESSION_SECRET=bbbb"));
  });

  it("keeps the quoting style of the line it edits", () => {
    const edited = editDevVars(`K="old"\n`, new Map([["K", "new"]]));
    expect(edited).toBe(`K="new"\n`);
  });

  it("carries an inline comment across a rotation", () => {
    const edited = editDevVars("API_KEY=old # prod key\n", new Map([["API_KEY", "new"]]));
    expect(edited).toBe("API_KEY=new # prod key\n");
  });

  it("leaves a key it was not asked about alone", () => {
    const edited = editDevVars(SAMPLE, new Map([["SESSION_SECRET", "bbbb"]]));
    expect(edited).toContain(`STRIPE_KEY="sk_live_x"`);
  });
});

describe("devVarsPath()", () => {
  it("resolves beside the config, not above the cwd", () => {
    expect(devVarsPath("/tmp/proj/wrangler.jsonc")).toBe("/tmp/proj/.dev.vars");
  });
});

describe("readDevVars() and writeDevVars()", () => {
  function makeFile(content: string): string {
    const path = join(mkdtempSync(join(tmpdir(), "foundry-devvars-")), ".dev.vars");
    writeFileSync(path, content, "utf-8");
    return path;
  }

  it("returns an empty list when the file is absent", () => {
    expect(readDevVars(join(tmpdir(), "definitely-absent", ".dev.vars"))).toEqual([]);
  });

  it("round-trips an edit through the file", () => {
    const path = makeFile(SAMPLE);
    writeDevVars(path, editDevVars(readFileSync(path, "utf-8"), new Map([["SESSION_SECRET", "cccc"]])));
    expect(readDevVars(path).find((v) => v.name === "SESSION_SECRET")?.value).toBe("cccc");
  });

  it("carries the file's own mode onto the replacement", () => {
    // The temp file is created 0600 and only then takes the original's mode, so a rotation
    // never widens permissions or leaves the new value world-readable in between.
    const path = makeFile("A=1\n");
    chmodSync(path, 0o600);
    writeDevVars(path, "A=2\n");
    expect(statSync(path).mode & 0o777).toBe(0o600);
  });
});
